/**
 * 海洋職人 (Ocean Craftsman) - 50種不重複珍稀魚種百科資料庫
 * 完全不重複，包含鼠魚系列深度專題、旗艦大師典藏、南美短鯛與精品脂鯉
 */

const SPECIES_DATA = [
  // ==========================================
  // GROUP 1: 鼠魚系列 - 長吻與高身珍稀類 (CW/Scleromystax)
  // ==========================================
  {
    id: "cory-01",
    code: "CW028",
    name: "帝王鼠",
    enName: "Imperial Corydoras",
    sciName: "Corydoras sp. CW028",
    category: "corydoras",
    categoryLabel: "長吻鼠魚",
    difficulty: 4,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 7.5,
    origin: "巴西亞馬遜黑水流域 (Rio Negro)",
    swimmingLayer: "底層水域 (Benthic)",
    temperament: "溫順沉穩 / 宜 5+ 群養",
    diet: "沉底肉食薄片、冷凍赤蟲、微細無脊椎動物",
    substrate: "極細純淨天然河砂 (防鬍鬚磨損)",
    waterFlow: "中等水流 / 超高溶氧",
    craftsmanTip: "帝王鼠吻部極長，對硝酸鹽及底砂細菌極度敏感。建議配置強力培菌系統與每週定期底砂虹吸。",
    citesStatus: "野生進口檢疫 / 珍稀典藏",
    accentColor: "#f5b942",
    badge: "CW028 典藏長吻",
    featured: false,
    image: "images/discus.jpg",
    tags: ["長吻", "黑水流域", "高溶氧喜好", "CW編號"]
  },
  {
    id: "cory-02",
    code: "CW051",
    name: "超級帝王鼠",
    enName: "Super Imperial Cory",
    sciName: "Corydoras sp. CW051",
    category: "corydoras",
    categoryLabel: "長吻鼠魚",
    difficulty: 5,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 6,
    sizeCm: 8.5,
    origin: "巴西內格羅河上游支流 (Upper Rio Negro)",
    swimmingLayer: "底層水域",
    temperament: "害羞沉著 / 愛陰暗處",
    diet: "活體豐年蝦、冷凍絲蚯蚓、高階沉底肉食錠",
    substrate: "超細圓潤矽砂 (粒徑 < 0.5mm)",
    waterFlow: "低至中等緩流",
    craftsmanTip: "背部具備如墨線般分明的粗黑條紋與高聳背鰭，需維持低 TDS (< 80 ppm) 與豐富沉木遮蔽物。",
    citesStatus: "高單價珍品 / 野生極稀少",
    accentColor: "#f5b942",
    badge: "CW051 夢幻逸品",
    featured: false,
    image: "images/discus.jpg",
    tags: ["長吻", "大師級", "低硬度", "極稀珍品"]
  },
  {
    id: "cory-03",
    code: "SYCHRI",
    name: "撒旦長吻鼠",
    enName: "Sychr's Corydoras",
    sciName: "Corydoras sychri",
    category: "corydoras",
    categoryLabel: "長吻鼠魚",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 6.0,
    origin: "秘魯納乃河 (Rio Nanay, Peru)",
    swimmingLayer: "底層水域",
    temperament: "溫和活躍 / 喜探索底質",
    diet: "沉底錠餌、冷凍赤蟲、微藻錠",
    substrate: "細緻中性砂",
    waterFlow: "中等水流",
    craftsmanTip: "經典長吻代表，具備白銀底色與黑斑眼帶。適應力較強，是進入長吻鼠領域的最佳基石品種。",
    citesStatus: "常規檢疫進口",
    accentColor: "#38bdf8",
    badge: "秘魯代表長吻",
    featured: false,
    image: "images/discus.jpg",
    tags: ["長吻", "秘魯水系", "經典品種"]
  },
  {
    id: "cory-04",
    code: "CW010-D",
    name: "黑金紅頭鼠",
    enName: "False Adolfoi Cory",
    sciName: "Corydoras duplicares",
    category: "corydoras",
    categoryLabel: "圓吻鼠魚",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 5.5,
    origin: "巴西內格羅河上游 (Rio Negro, Brazil)",
    swimmingLayer: "底層至中下層",
    temperament: "活潑好動 / 群聚性極佳",
    diet: "微粒沉底料、紅蟲、豐年蝦幼蟲",
    substrate: "細砂或細粒黑金砂",
    waterFlow: "中等水流",
    craftsmanTip: "頭部具備閃耀金黃橘色光斑，背部粗黑背線比阿道夫鼠更寬闊，在弱酸軟水下發色如燃燒火金。",
    citesStatus: "穩定人工繁殖 / 野生兼具",
    accentColor: "#f97316",
    badge: "金光頭頂經典",
    featured: false,
    image: "images/discus.jpg",
    tags: ["金頭", "溫和", "新手友善", "群游"]
  },
  {
    id: "cory-05",
    code: "ADOLFOI",
    name: "阿道夫鼠",
    enName: "Adolfo's Corydoras",
    sciName: "Corydoras adolfoi",
    category: "corydoras",
    categoryLabel: "短吻鼠魚",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 6,
    sizeCm: 5.5,
    origin: "巴西內格羅河流域 (Rio Negro Basin)",
    swimmingLayer: "底層水域",
    temperament: "極度溫和",
    diet: "微細底棲沉糧、無脊椎生物",
    substrate: "極細白沙或熱帶雨林砂",
    waterFlow: "穩定微流",
    craftsmanTip: "以發現者 Adolfo Schwartz 命名。辨識核心為頭部金橘斑與背部細緻銳利的黑線，與黑金紅頭呈現雙璧之美。",
    citesStatus: "經典名品",
    accentColor: "#fbbf24",
    badge: "亞馬遜經典名種",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短吻", "金色亮斑", "軟水育成"]
  },
  {
    id: "cory-06",
    code: "BARBATUS",
    name: "高身蝙蝠鼠",
    enName: "Bearded Corydoras",
    sciName: "Scleromystax barbatus",
    category: "corydoras",
    categoryLabel: "蝙蝠鼠屬",
    difficulty: 4,
    tempMin: 18,
    tempMax: 24,
    phMin: 6.0,
    phMax: 7.4,
    ghMin: 4,
    ghMax: 12,
    sizeCm: 10.0,
    origin: "巴西東南部沿海溪流 (Coastal Streams, Brazil)",
    swimmingLayer: "底層至底木區",
    temperament: "公魚具領域性 / 體型壯碩",
    diet: "高蛋白沉底餌、甲殼類碎肉、赤蟲",
    substrate: "天然卵石與細河砂交錯",
    waterFlow: "強水流 / 低溫冷泉水",
    craftsmanTip: "本種為鼠魚界的巨型重裝坦克，雄魚成熟時面頰會長滿如刷子般的長鬚金毛。性喜冷涼水溫 (18~23°C)，夏天務必配置冷卻設備。",
    citesStatus: "珍稀沿岸原生物種",
    accentColor: "#2dd4bf",
    badge: "10cm 巨型冷水名品",
    featured: false,
    image: "images/discus.jpg",
    tags: ["冷水性", "巨型", "長鬍腮刷", "Scleromystax"]
  },
  {
    id: "cory-07",
    code: "PRIONOTOS",
    name: "長吻蝙蝠鼠",
    enName: "Prionotos Corydoras",
    sciName: "Scleromystax prionotos",
    category: "corydoras",
    categoryLabel: "蝙蝠鼠屬",
    difficulty: 4,
    tempMin: 19,
    tempMax: 24,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 7.5,
    origin: "巴西大西洋沿岸熱帶雨林溪流",
    swimmingLayer: "底層水域",
    temperament: "活躍善泳",
    diet: "底棲雜食、水生昆蟲幼蟲",
    substrate: "細緻天然黑河砂",
    waterFlow: "急流造浪喜好",
    craftsmanTip: "身軀修長，具備如金屬雕刻般的迷宮網紋。對高溫極度不耐，溶氧量需維持飽和以上。",
    citesStatus: "野生限量採集",
    accentColor: "#38bdf8",
    badge: "迷宮雕紋長吻",
    featured: false,
    image: "images/discus.jpg",
    tags: ["長吻", "冷涼水系", "急流"]
  },
  {
    id: "cory-08",
    code: "SUP-SCHW",
    name: "超級舒瓦茲鼠",
    enName: "Super Schwarzi Cory",
    sciName: "Corydoras super schwarzi",
    category: "corydoras",
    categoryLabel: "高鰭長身鼠",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 7.0,
    origin: "巴西普魯斯河 (Rio Purus, Brazil)",
    swimmingLayer: "底層水域",
    temperament: "端莊威嚴 / 喜展鰭",
    diet: "優質沉底肉食錠、冷凍紅蟲",
    substrate: "超細圓潤底砂",
    waterFlow: "中等水流",
    craftsmanTip: "頂級公魚的第一背鰭硬棘如白色長矛般高聳入雲，兩側貫穿純黑鋼鐵平行線，是職人缸中極具視覺張力的主角。",
    citesStatus: "野生捕撈精選",
    accentColor: "#f5b942",
    badge: "超長白色天線背鰭",
    featured: false,
    image: "images/discus.jpg",
    tags: ["高鰭", "長天線", "普魯斯河", "觀賞極致"]
  },

  // ==========================================
  // GROUP 2: 鼠魚系列 - 短吻、圓吻與侏儒類
  // ==========================================
  {
    id: "cory-09",
    code: "PANDA",
    name: "熊貓鼠",
    enName: "Panda Corydoras",
    sciName: "Corydoras panda",
    category: "corydoras",
    categoryLabel: "短吻鼠魚",
    difficulty: 1,
    tempMin: 20,
    tempMax: 25,
    phMin: 6.0,
    phMax: 7.4,
    ghMin: 2,
    ghMax: 10,
    sizeCm: 4.5,
    origin: "秘魯烏卡亞利河流域 (Rio Ucayali)",
    swimmingLayer: "底層水域",
    temperament: "極度討喜 / 親人活潑",
    diet: "全功能鼠魚沉底餅、底棲藻類錠、豐年蝦",
    substrate: "細緻白色石英砂或熱帶砂",
    waterFlow: "柔和至中等",
    craftsmanTip: "眼帶黑眼圈、尾柄黑點，如大熊貓般可愛。飼養關鍵在於維持水溫勿高於 27°C，新進魚隻需漸進對水防緊迫。",
    citesStatus: "廣泛人工繁殖",
    accentColor: "#e2e8f0",
    badge: "水族人氣第一",
    featured: true,
    image: "images/discus.jpg",
    tags: ["短吻", "新手首選", "人氣王", "親人"]
  },
  {
    id: "cory-10",
    code: "STERBAI",
    name: "金翅珍珠鼠",
    enName: "Sterba's Corydoras",
    sciName: "Corydoras sterbai",
    category: "corydoras",
    categoryLabel: "圓吻鼠魚",
    difficulty: 1,
    tempMin: 24,
    tempMax: 30,
    phMin: 6.0,
    phMax: 7.6,
    ghMin: 2,
    ghMax: 12,
    sizeCm: 6.5,
    origin: "巴西瓜波雷河流域 (Rio Guapore, Brazil)",
    swimmingLayer: "底層水域",
    temperament: "強健大方 / 無畏懼感",
    diet: "沉底葷素各類顆粒飼料、紅蟲",
    substrate: "中性河砂、黑金砂",
    waterFlow: "中等水流",
    craftsmanTip: "頭部佈滿如珍珠般的繁星點點，胸鰭閃爍亮橘金色。本種耐高溫能力極強 (可達 30°C)，是七彩神仙與埃及神仙缸的最佳清潔隊長。",
    citesStatus: "大量人工繁育 / 野生精選",
    accentColor: "#f97316",
    badge: "耐高溫神仙最佳混養",
    featured: true,
    image: "images/discus.jpg",
    tags: ["耐高溫", "珍珠點", "七彩搭檔", "入門強健"]
  },
  {
    id: "cory-11",
    code: "BURGESS",
    name: "紅頭鼠 (伯吉斯鼠)",
    enName: "Burgess's Corydoras",
    sciName: "Corydoras burgessi",
    category: "corydoras",
    categoryLabel: "短吻鼠魚",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.6,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 5,
    sizeCm: 5.0,
    origin: "巴西內格羅河流域 (Rio Unini)",
    swimmingLayer: "底層水域",
    temperament: "溫文儒雅",
    diet: "微細赤蟲、水蚤、細微沉餌",
    substrate: "極細弱酸性河砂",
    waterFlow: "柔和靜水流",
    craftsmanTip: "頂部橘紅光點比阿道夫鼠更顯圓潤，背鰭根部有單點黑塊。水質維持弱酸軟水時，頭頂如戴紅寶石王冠。",
    citesStatus: "野生捕撈",
    accentColor: "#ef4444",
    badge: "紅寶石王冠短吻",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短吻", "紅頭", "弱酸軟水"]
  },
  {
    id: "cory-12",
    code: "PYGMAEUS",
    name: "精靈鼠 (侏儒鼠)",
    enName: "Pygmy Corydoras",
    sciName: "Corydoras pygmaeus",
    category: "corydoras",
    categoryLabel: "侏儒迷你鼠",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.2,
    phMax: 7.4,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 2.5,
    origin: "巴西與秘魯境內馬代拉河流域 (Rio Madeira)",
    swimmingLayer: "中層中游與水草葉面",
    temperament: "極度熱愛百隻大群游",
    diet: "草履蟲、豐年蝦無節幼蟲、微米沉粉",
    substrate: "水草泥、細緻底砂",
    waterFlow: "微弱柔流",
    craftsmanTip: "不同於一般只在底砂爬行的鼠魚，精靈鼠愛如直升機般懸停於水草葉片與中層水域群游。極適合微型水草造景缸。",
    citesStatus: "穩定人工繁殖",
    accentColor: "#22c55e",
    badge: "2.5cm 水草缸中層群游",
    featured: false,
    image: "images/discus.jpg",
    tags: ["侏儒", "中層群游", "草缸絕配", "迷你"]
  },
  {
    id: "cory-13",
    code: "HASTATUS",
    name: "月光鼠",
    enName: "Tail Spot Pygmy Cory",
    sciName: "Corydoras hastatus",
    category: "corydoras",
    categoryLabel: "侏儒迷你鼠",
    difficulty: 3,
    tempMin: 20,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 2.8,
    origin: "巴西與巴拉圭瓜波雷河流域",
    swimmingLayer: "中層水中懸浮",
    temperament: "小巧靈動 / 喜大群體",
    diet: "微細水生浮游生物、輪蟲、微粉末餌",
    substrate: "水草底床 / 細砂",
    waterFlow: "弱緩水流",
    craftsmanTip: "尾柄具備黑白如滿月般的耀眼菱形光斑，雙鰭高頻振動如蜂鳥般懸停中水。是水族微距愛好者的極致微型名種。",
    citesStatus: "人工與野生並存",
    accentColor: "#a855f7",
    badge: "蜂鳥懸停尾月斑",
    featured: false,
    image: "images/discus.jpg",
    tags: ["迷你", "懸停", "尾斑月光"]
  },
  {
    id: "cory-14",
    code: "HABROSUS",
    name: "娃娃鼠",
    enName: "Salt and Pepper Cory",
    sciName: "Corydoras habrosus",
    category: "corydoras",
    categoryLabel: "侏儒迷你鼠",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.2,
    phMax: 7.5,
    ghMin: 2,
    ghMax: 9,
    sizeCm: 3.2,
    origin: "委內瑞拉與哥倫比亞奧里諾科河流域",
    swimmingLayer: "底層水域",
    temperament: "溫馴勤勞 / 勤快耕砂",
    diet: "小型沉底顆粒、微蟲、赤蟲碎片",
    substrate: "細緻白砂",
    waterFlow: "中弱水流",
    craftsmanTip: "體表密佈如胡椒鹽般的灰黑碎斑，保留標準底棲鼠魚的勤奮耕砂習性，卻只有 3 公分迷你身軀，小缸必備首選。",
    citesStatus: "常態供應",
    accentColor: "#64748b",
    badge: "胡椒鹽迷你底棲",
    featured: false,
    image: "images/discus.jpg",
    tags: ["侏儒", "胡椒鹽", "勤奮耕砂"]
  },
  {
    id: "cory-15",
    code: "EQUES",
    name: "黑箭鼠 (紅橘黑箭)",
    enName: "Orange Collar Cory",
    sciName: "Corydoras eques",
    category: "corydoras",
    categoryLabel: "圓吻鼠魚",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 6,
    sizeCm: 5.0,
    origin: "巴西亞馬遜流域科達哈斯周邊湖泊",
    swimmingLayer: "底層至中層",
    temperament: "活潑成群",
    diet: "沉底錠餌、冷凍豐年蝦",
    substrate: "細緻暗色天然砂",
    waterFlow: "弱至中等",
    craftsmanTip: "深藍墨黑如天鵝絨的身軀，配上一圈熾熱的橘紅色圍巾領斑，游動時如黑箭劃破水面，發色極富深邃藝術感。",
    citesStatus: "野生捕撈季節限定",
    accentColor: "#ea580c",
    badge: "天鵝絨黑橘領巾",
    featured: false,
    image: "images/discus.jpg",
    tags: ["圓吻", "黑金深邃", "橘領巾"]
  },
  {
    id: "cory-16",
    code: "RABAUTI",
    name: "紅肚鼠 (拉氏鼠)",
    enName: "Rabaut's Corydoras",
    sciName: "Corydoras rabauti",
    category: "corydoras",
    categoryLabel: "短吻鼠魚",
    difficulty: 2,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 5.8,
    origin: "巴西亞馬遜上游雅瓦里河 (Rio Javari)",
    swimmingLayer: "底層水域",
    temperament: "沉穩和平",
    diet: "微細沉底料、絲蚯蚓、紅蟲",
    substrate: "細圓砂",
    waterFlow: "中等水流",
    craftsmanTip: "幼魚時期呈現全身斑斕的橘金與黑條紋，成魚後腹部透出厚實的暖橘紅光，背部有一條優美斜背黑帶貫穿尾柄。",
    citesStatus: "經典穩定引進",
    accentColor: "#f97316",
    badge: "暖橘紅肚腹色澤",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短吻", "暖橘腹", "亞馬遜原生"]
  },
  {
    id: "cory-17",
    code: "VIRGINAE",
    name: "印第安鼠 (白狐狸鼠)",
    enName: "Virginia's Cory",
    sciName: "Corydoras virginae",
    category: "corydoras",
    categoryLabel: "短吻鼠魚",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 6.0,
    origin: "秘魯烏卡亞利河 (Rio Ucayali, Peru)",
    swimmingLayer: "底層水域",
    temperament: "親切好動",
    diet: "各類沉底飼料、冷凍紅蟲",
    substrate: "天然石英細砂",
    waterFlow: "中等水流",
    craftsmanTip: "面部具有經典印第安戰士般的斜面黑面罩，身體銀白透光，背部黑斑如馬鞍般分明，是耐看且易活的經典短吻。",
    citesStatus: "大量引進",
    accentColor: "#38bdf8",
    badge: "印第安戰士黑眼罩",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短吻", "馬鞍斑", "秘魯產"]
  },
  {
    id: "cory-18",
    code: "BLACK-VEN",
    name: "委內瑞拉黑鼠",
    enName: "Black Venezuela Cory",
    sciName: "Corydoras schultzei 'Black'",
    category: "corydoras",
    categoryLabel: "圓吻黑化品系",
    difficulty: 2,
    tempMin: 21,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 5.5,
    origin: "人工純化黑化育種品系 (原種源自委內瑞拉)",
    swimmingLayer: "底層水域",
    temperament: "大膽不懼生 / 活動力充沛",
    diet: "全系列沉性飼料、高蛋白肉食餌",
    substrate: "白色細砂 (黑白強烈對比)",
    waterFlow: "中等水流",
    craftsmanTip: "全身如黑曜石般通體黑亮，胸鰭泛有微紅銅光澤。若鋪設白砂造景，黑亮的身段在缸中宛如流動的黑珍珠。",
    citesStatus: "高端人工培育種",
    accentColor: "#334155",
    badge: "全黑黑曜石名品",
    featured: false,
    image: "images/discus.jpg",
    tags: ["純黑", "黑曜石", "人工純化", "高對比"]
  },

  // ==========================================
  // GROUP 3: 鼠魚系列 - 雷射、翡翠與巨斑珍稀類
  // ==========================================
  {
    id: "cory-19",
    code: "CW010",
    name: "黃金雷射鼠",
    enName: "Gold Laser Cory",
    sciName: "Corydoras sp. CW010",
    category: "corydoras",
    categoryLabel: "雷射金屬鼠",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 6.0,
    origin: "秘魯烏卡亞利河與馬拉尼翁河上游",
    swimmingLayer: "底層水域",
    temperament: "敏捷活潑",
    diet: "豐年蝦、微粒沉底料、赤蟲",
    substrate: "深色細砂 (加強金屬反光)",
    waterFlow: "中等水流",
    craftsmanTip: "側線貫穿一條如同通電般高亮度的金色螢光雷射寬帶，在夜間微光或頂燈投射下閃耀奪目金屬光芒。",
    citesStatus: "產地野生直輸",
    accentColor: "#eab308",
    badge: "CW010 霓虹電光金線",
    featured: true,
    image: "images/discus.jpg",
    tags: ["雷射鼠", "金屬光澤", "電光金線", "秘魯產"]
  },
  {
    id: "cory-20",
    code: "CW009",
    name: "綠線雷射鼠",
    enName: "Green Laser Cory",
    sciName: "Corydoras sp. CW009",
    category: "corydoras",
    categoryLabel: "雷射金屬鼠",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 6.0,
    origin: "秘魯烏卡亞利河支流 (Rio Ucayali, Peru)",
    swimmingLayer: "底層水域",
    temperament: "溫和活躍",
    diet: "優質沉底顆粒、無節幼蟲、水蚤",
    substrate: "極細暗色河砂",
    waterFlow: "中等水流",
    craftsmanTip: "同屬 CW 夢幻雷射系列，側線散發如綠翡翠極光般的祖母綠電光色澤，水草造景缸的視覺焦點。",
    citesStatus: "野生引進",
    accentColor: "#10b981",
    badge: "CW009 翡翠極光綠線",
    featured: false,
    image: "images/discus.jpg",
    tags: ["雷射鼠", "翡翠綠光", "極光色系"]
  },
  {
    id: "cory-21",
    code: "CW023",
    name: "橘紅雷射鼠",
    enName: "Orange Laser Cory",
    sciName: "Corydoras sp. CW023",
    category: "corydoras",
    categoryLabel: "雷射金屬鼠",
    difficulty: 4,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 6.0,
    origin: "秘魯亞馬遜盆地深處溪流",
    swimmingLayer: "底層水域",
    temperament: "高貴沉穩",
    diet: "冷凍赤蟲、白蟲、高階底棲肉食餌",
    substrate: "細緻天然黑泥砂",
    waterFlow: "中等溶氧水流",
    craftsmanTip: "側線呈現熾熱橘紅色熔岩雷射光帶，數量較金/綠雷射更為稀少，維持弱酸軟水能讓紅帶厚度與亮度達到極致。",
    citesStatus: "珍稀野生限量",
    accentColor: "#f97316",
    badge: "CW023 熔岩赤橘雷射",
    featured: false,
    image: "images/discus.jpg",
    tags: ["雷射鼠", "熔岩赤橘", "珍稀限定"]
  },
  {
    id: "cory-22",
    code: "BROCHIS-01",
    name: "綠面翡翠鼠 (巨型青銅鼠)",
    enName: "Emerald Brochis",
    sciName: "Brochis splendens",
    category: "corydoras",
    categoryLabel: "青銅鼠屬 (Brochis)",
    difficulty: 2,
    tempMin: 21,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.8,
    ghMin: 3,
    ghMax: 15,
    sizeCm: 8.5,
    origin: "亞馬遜流域廣布 (巴西、秘魯、厄瓜多)",
    swimmingLayer: "底層至中層巡游",
    temperament: "大方勇猛 / 搶食迅速",
    diet: "全吃雜食、沉底大顆粒、各類凍餌",
    substrate: "中性細砂 / 卵石",
    waterFlow: "強至中等",
    craftsmanTip: "具備多達 10~12 根背鰭鰭條（一般鼠魚僅 7~8 根），身披如青銅鎧甲般的綠色金屬光澤，厚重如綠色戰艦。",
    citesStatus: "經典大型常規種",
    accentColor: "#059669",
    badge: "8.5cm 青銅巨背鰭鎧甲",
    featured: false,
    image: "images/discus.jpg",
    tags: ["Brochis", "綠金屬光", "大體型", "強健"]
  },
  {
    id: "cory-23",
    code: "BROCHIS-02",
    name: "巨型長吻巨斑青銅鼠",
    enName: "Hog-nosed Brochis",
    sciName: "Brochis multiradiatus",
    category: "corydoras",
    categoryLabel: "青銅鼠屬 (Brochis)",
    difficulty: 4,
    tempMin: 21,
    tempMax: 25,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 11.5,
    origin: "厄瓜多與秘魯亞馬遜上游 (Rio Pastaza)",
    swimmingLayer: "底層水域",
    temperament: "王者霸氣 / 穩健",
    diet: "高蛋白沉底餌料、碎蝦肉、大型紅蟲",
    substrate: "純天然細緻河砂",
    waterFlow: "強大過濾與造流",
    craftsmanTip: "青銅鼠屬中的終極霸主，背鰭鰭條多達 17 根以上，體長可破 11 公分。吻部如野豬般下探掘砂，需配備強效底層過濾。",
    citesStatus: "野生高原稀有採集",
    accentColor: "#0d9488",
    badge: "11.5cm 鼠魚家族超級霸主",
    featured: false,
    image: "images/discus.jpg",
    tags: ["Brochis", "11cm極限巨體", "野豬長吻"]
  },
  {
    id: "cory-24",
    code: "BOESEMANI",
    name: "國王黑金鼠 (博氏鼠)",
    enName: "Boeseman's Cory",
    sciName: "Corydoras boesemani",
    category: "corydoras",
    categoryLabel: "珍稀短吻鼠",
    difficulty: 4,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 5.5,
    origin: "蘇利南黑水雨林溪流 (Suriname)",
    swimmingLayer: "底層水域",
    temperament: "端莊害羞",
    diet: "微細高級沉餅、無脊椎動物",
    substrate: "極細白矽砂",
    waterFlow: "微弱清澈軟流",
    craftsmanTip: "來自神秘蘇利南產區，身上擁有兩枚如印章般厚實深邃的對稱黑印。水質需長期保持純淨無氯與低硝酸鹽。",
    citesStatus: "蘇利南野生配額限制",
    accentColor: "#f5b942",
    badge: "蘇利南雙黑印珍品",
    featured: false,
    image: "images/discus.jpg",
    tags: ["蘇利南", "稀有產區", "雙黑印"]
  },
  {
    id: "cory-25",
    code: "GOSSEI",
    name: "金珍珠鼠 (高斯鼠)",
    enName: "Gosse's Corydoras",
    sciName: "Corydoras gossei",
    category: "corydoras",
    categoryLabel: "圓吻亮翅鼠",
    difficulty: 3,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 6.5,
    origin: "巴西馬代拉河流域 (Rio Mamore / Madeira)",
    swimmingLayer: "底層水域",
    temperament: "溫文沉著",
    diet: "沉底肉食顆粒、豐年蝦、赤蟲",
    substrate: "圓滑暗色細砂",
    waterFlow: "中等水流",
    craftsmanTip: "背鰭與胸鰭硬棘呈現純度極高的鮮艷亮黃金光，體色呈現深石板灰，與金翅珍珠鼠並稱金鰭雙傑，但金珍珠色澤更顯莊重內斂。",
    citesStatus: "野生定期批次",
    accentColor: "#eab308",
    badge: "純亮黃金硬棘雙鰭",
    featured: false,
    image: "images/discus.jpg",
    tags: ["金鰭", "石板灰身", "馬代拉河"]
  },
  {
    id: "cory-26",
    code: "PANTANAL",
    name: "巨無霸網球鼠 (潘塔納爾鼠)",
    enName: "Pantanal Cory",
    sciName: "Corydoras pantanalensis",
    category: "corydoras",
    categoryLabel: "大體型變色鼠",
    difficulty: 4,
    tempMin: 20,
    tempMax: 25,
    phMin: 6.2,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 8.5,
    origin: "巴西潘塔納爾大濕地 (Pantanal Wetland)",
    swimmingLayer: "底層水域",
    temperament: "發情期公魚霸氣游弋",
    diet: "各類沉底大顆粒、活紅蟲、蝦肉碎",
    substrate: "細緻天然濕地砂",
    waterFlow: "中等造流",
    craftsmanTip: "水族界著名的「變色龍鼠」，成年雄魚在繁殖季節會全身轉變為極具震撼力的黑綠豹紋金屬網格，體長可達 8.5 公分。",
    citesStatus: "季節性野生大濕地採集",
    accentColor: "#14b8a6",
    badge: "發情期金屬豹網巨公魚",
    featured: false,
    image: "images/discus.jpg",
    tags: ["變色性", "潘塔納爾", "網球豹紋", "大體型"]
  },
  {
    id: "cory-27",
    code: "TRILINEATUS",
    name: "白金豹鼠 (三線豹鼠)",
    enName: "Three-stripe Cory",
    sciName: "Corydoras trilineatus",
    category: "corydoras",
    categoryLabel: "短吻豹斑鼠",
    difficulty: 1,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 2,
    ghMax: 12,
    sizeCm: 5.5,
    origin: "秘魯、哥倫比亞亞馬遜上游盆地",
    swimmingLayer: "底層水域",
    temperament: "親民活躍",
    diet: "各類鼠魚沉糧、薄片殘餌、紅蟲",
    substrate: "各類中細底砂",
    waterFlow: "中等水流",
    craftsmanTip: "常被誤稱為花豹鼠，但其頭部密佈如精密蕾絲般的迷宮線條，背鰭頂端有鮮明黑旗，是性價比與美感兼備的入門首選。",
    citesStatus: "常態引進與人工繁殖",
    accentColor: "#94a3b8",
    badge: "蕾絲迷宮豹紋名品",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短吻", "迷宮紋", "耐養強健", "入門首選"]
  },
  {
    id: "cory-28",
    code: "ROBUSTUS",
    name: "皇室巨斑鼠 (羅伯斯鼠)",
    enName: "Robust Giant Cory",
    sciName: "Corydoras robustus",
    category: "corydoras",
    categoryLabel: "巨型長吻鼠",
    difficulty: 5,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 6,
    sizeCm: 9.5,
    origin: "巴西普魯斯河流域 (Rio Purus Basin)",
    swimmingLayer: "底層水域",
    temperament: "莊重威嚴 / 需大空間",
    diet: "高階沉底肉食錠、冷凍紅蟲、無脊椎",
    substrate: "特級純淨超細天然砂",
    waterFlow: "強勁溶氧水流",
    craftsmanTip: "長吻鼠魚中的終極皇冠。背鰭極長如長槍，體格厚重壯碩，對水質清潔度有著極致的要求，是資深玩家的終身夢幻物種。",
    citesStatus: "野生頂級限量收藏",
    accentColor: "#f5b942",
    badge: "9.5cm 長吻終極巨皇",
    featured: false,
    image: "images/discus.jpg",
    tags: ["長吻", "9.5cm頂級", "大師夢幻種", "普魯斯河"]
  },

  // ==========================================
  // GROUP 4: 旗艦代表珍稀觀賞魚 (Artisanal Icons)
  // ==========================================
  {
    id: "flag-01",
    code: "RED-AROWANA",
    name: "頂級特級亞洲紅龍",
    enName: "Super Red Asian Arowana",
    sciName: "Scleropages formosus",
    category: "flagship",
    categoryLabel: "大師旗艦魚",
    difficulty: 4,
    tempMin: 26,
    tempMax: 30,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 65.0,
    origin: "印尼加里曼丹卡普阿斯河流域 (Kapuas River)",
    swimmingLayer: "頂層水域 (Surface Pelagic)",
    temperament: "霸氣威嚴 / 具領地意識",
    diet: "優質蝦肉、麵包蟲、杜比亞蟑螂、頂級龍魚條狀浮糧",
    substrate: "裸缸飼育 (防磨損) 或極細黑金底砂",
    waterFlow: "中等穩定循環水流",
    craftsmanTip: "魚鱗六排全過背、辣椒紅發色深邃如火。飼養關鍵在於維持穩定水溫 28°C、充裕游動空間 (建議 5 尺以上缸體) 與防跳缸嚴密頂蓋。",
    citesStatus: "CITES 附錄 I (具晶片與合法證書)",
    accentColor: "#dc2626",
    badge: "CITES I 級水下王者",
    featured: true,
    image: "images/arowana.jpg",
    tags: ["亞洲龍魚", "過背辣椒紅", "晶片身分", "頂級王者"]
  },
  {
    id: "flag-02",
    code: "HECKEL-DISCUS",
    name: "黑格爾七彩神仙 (野生黑格爾)",
    enName: "Heckel Wild Discus",
    sciName: "Symphysodon discus 'Heckel'",
    category: "flagship",
    categoryLabel: "大師旗艦魚",
    difficulty: 5,
    tempMin: 28,
    tempMax: 31,
    phMin: 4.8,
    phMax: 6.2,
    ghMin: 1,
    ghMax: 4,
    sizeCm: 18.0,
    origin: "巴西內格羅河黑水流域 (Rio Negro)",
    swimmingLayer: "中層水域",
    temperament: "優雅沉靜 / 喜群游",
    diet: "牛心漢堡、特級赤蟲、微細無脊椎凍餌",
    substrate: "極細白沙或沉木裸缸",
    waterFlow: "柔和緩慢無死角水流",
    craftsmanTip: "野生七彩之皇，第五暗黑貫穿垂直棟線是其靈魂標誌。要求極致的黑水弱酸超軟水 (pH 5.0~5.8, TDS < 50 ppm)，考驗職人調水造詣。",
    citesStatus: "野生季節性採集",
    accentColor: "#0ea5e9",
    badge: "熱帶魚之皇野生黑格爾",
    featured: true,
    image: "images/discus.jpg",
    tags: ["熱帶魚之王", "極軟黑水", "第五棟線", "七彩神仙"]
  },
  {
    id: "flag-03",
    code: "CROWN-BETTA",
    name: "皇家藍冠尾鬥魚 (王者之冠)",
    enName: "Crowntail Royal Blue Betta",
    sciName: "Betta splendens 'Crowntail'",
    category: "flagship",
    categoryLabel: "大師旗艦魚",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 6.5,
    origin: "泰國湄公河流域 (人工頂級培育)",
    swimmingLayer: "中上層 / 迷鰓呼吸",
    temperament: "雄魚好鬥 / 展鰭極致",
    diet: "鬥魚專用小顆粒高蛋白浮糧、豐年蝦、赤蟲",
    substrate: "水草泥、欖仁葉沉積床",
    waterFlow: "極微弱靜水",
    craftsmanTip: "鰭條分支縮減率達 33%~50%，如國王皇冠般根根挺立銳利。每週定期進行 10 分鐘照鏡展鰭訓練，能鍛鍊鰭膜張力與霸氣體態。",
    citesStatus: "人工培育大師品系",
    accentColor: "#3b82f6",
    badge: "針芒皇冠極致展鰭",
    featured: true,
    image: "images/betta.jpg",
    tags: ["冠尾", "迷鰓魚", "皇家藍", "鏡面訓練"]
  },
  {
    id: "flag-04",
    code: "L046-ZEBRA",
    name: "帝王斑馬異型 (L046)",
    enName: "Imperial Zebra Pleco L046",
    sciName: "Hypancistrus zebra",
    category: "plecos",
    categoryLabel: "珍稀異型魚",
    difficulty: 4,
    tempMin: 27,
    tempMax: 31,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 9.5,
    origin: "巴西欣谷河急流深處 (Rio Xingu, Brazil)",
    swimmingLayer: "岩縫深處底層",
    temperament: "害羞夜行 / 喜陶瓷繁殖甕",
    diet: "肉食性沉底顆粒、無節幼蟲、豐年蝦肉",
    substrate: "火山岩塊、深色卵石與陶瓷洞穴",
    waterFlow: "超強急流 / 90%+ 飽和溶氧",
    craftsmanTip: "黑白分明的斑馬條紋與湛藍眼眸，被譽為「水族黑白國寶」。需維持水溫 28~30°C 與強勁水流，是異型玩家終極繁殖殿堂物種。",
    citesStatus: "CITES 附錄 III / 巴西瀕危保護",
    accentColor: "#38bdf8",
    badge: "L046 水族黑白國寶",
    featured: true,
    image: "images/pleco.jpg",
    tags: ["L046", "欣谷河", "黑白條紋", "高溫高氧"]
  },
  {
    id: "flag-05",
    code: "L014-SUNSHINE",
    name: "黃金達摩異型 (L014)",
    enName: "Sunshine Pleco L014",
    sciName: "Scobinancistrus aureatus",
    category: "plecos",
    categoryLabel: "珍稀異型魚",
    difficulty: 3,
    tempMin: 26,
    tempMax: 30,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 30.0,
    origin: "巴西欣谷河流域 (Rio Xingu)",
    swimmingLayer: "底層岩石區",
    temperament: "體型壯碩 / 沉穩",
    diet: "肉食螺肉、蝦肉顆粒、異型大型葷食錠",
    substrate: "粗卵石、大型沉木",
    waterFlow: "強大水流",
    craftsmanTip: "全身覆蓋著如陽光熔金般的鮮黃鰭邊與星芒斑點，齒型特化專為啃食軟體水生動物，成魚體型壯觀極具魄力。",
    citesStatus: "野生捕撈限量",
    accentColor: "#eab308",
    badge: "L014 欣谷河流金艷陽",
    featured: false,
    image: "images/pleco.jpg",
    tags: ["L014", "金黃鰭緣", "大型異型", "欣谷河"]
  },
  {
    id: "flag-06",
    code: "PLATINUM-GUPPY",
    name: "白金全紅白子孔雀魚",
    enName: "Platinum Full Red Albino Guppy",
    sciName: "Poecilia reticulata 'Albino Full Red'",
    category: "flagship",
    categoryLabel: "大師旗艦魚",
    difficulty: 2,
    tempMin: 23,
    tempMax: 27,
    phMin: 6.8,
    phMax: 7.8,
    ghMin: 6,
    ghMax: 14,
    sizeCm: 5.0,
    origin: "台灣大師級純系純化培育",
    swimmingLayer: "中上層水域",
    temperament: "溫馴愛游動",
    diet: "微細高蛋白孔雀魚專用浮水粉糧、豐年蝦幼蟲",
    substrate: "中性細砂 / 水草",
    waterFlow: "緩慢平穩水流",
    craftsmanTip: "紅寶石般的赤紅眼眸，胸腹覆蓋著如液態金屬般的白金厚甲，尾鰭大噴發如鮮紅絲絨，是活餌培育與水質維護的純系名品。",
    citesStatus: "台灣大賽冠軍血統",
    accentColor: "#f43f5e",
    badge: "台灣純系大賽冠軍血統",
    featured: true,
    image: "images/guppy.jpg",
    tags: ["孔雀魚", "白金厚甲", "白子紅眼", "大賽品系"]
  },
  {
    id: "flag-07",
    code: "BLACK-DIAMOND",
    name: "皇冠黑白魟魚 (黑鑽石魟)",
    enName: "Black Diamond Stingray",
    sciName: "Potamotrygon leopoldi",
    category: "flagship",
    categoryLabel: "大師旗艦魚",
    difficulty: 5,
    tempMin: 26,
    tempMax: 29,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 60.0,
    origin: "巴西欣谷河流域 (人工頂級黑鑽繁殖)",
    swimmingLayer: "底層平鋪水域",
    temperament: "底棲滑翔霸主",
    diet: "鮮蝦仁、泥鰍段、特級魟魚沉底肉食大粒",
    substrate: "超細圓潤河砂 (厚度不超過 1cm) 或裸缸",
    waterFlow: "強大滴流培菌與排污系統",
    craftsmanTip: "盤體如黑漆鋼琴木上鑲嵌大顆白色甜甜圈鑽石斑，盤緣點綴密實滿天星。對水中毒素極度敏感，需具備強大的硝化過濾。",
    citesStatus: "CITES 附錄 II (合法晶片登錄)",
    accentColor: "#cbd5e1",
    badge: "黑鑽甜甜圈皇冠大師級",
    featured: false,
    image: "images/discus.jpg",
    tags: ["黑鑽魟", "甜甜圈斑", "底棲滑翔", "CITES II"]
  },

  // ==========================================
  // GROUP 5: 南美短鯛與精緻慈鯛 (Dwarf Cichlids)
  // ==========================================
  {
    id: "cich-01",
    code: "BITAENIATA",
    name: "酋長短鯛 (雙線短鯛)",
    enName: "Two-striped Apisto",
    sciName: "Apistogramma bitaeniata",
    category: "cichlids",
    categoryLabel: "南美短鯛",
    difficulty: 3,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.0,
    phMax: 6.5,
    ghMin: 1,
    ghMax: 5,
    sizeCm: 7.0,
    origin: "秘魯與巴西境內亞馬遜河上游黑水支流",
    swimmingLayer: "中下層水草與沉木區",
    temperament: "公魚具領域展示慾望",
    diet: "活體豐年蝦、冷凍水蚤、微細肉食薄片",
    substrate: "細緻酸性天然泥砂",
    waterFlow: "微弱平緩水流",
    craftsmanTip: "雄魚背鰭前數棘如古代印第安酋長羽冠般高聳，雙琴尾如飄帶般修長，在欖仁葉浸潤的微酸黑水中散發藍橘交織光芒。",
    citesStatus: "野生捕撈季節種",
    accentColor: "#38bdf8",
    badge: "羽冠高背鰭酋長雙琴尾",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短鯛", "酋長", "雙琴尾", "黑水微酸"]
  },
  {
    id: "cich-02",
    code: "CACATUOIDES",
    name: "霸王短鯛 (三叉超紅尾)",
    enName: "Cockatoo Cichlid",
    sciName: "Apistogramma cacatuoides",
    category: "cichlids",
    categoryLabel: "南美短鯛",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 8.0,
    origin: "亞馬遜河上游秘魯與哥倫比亞淺水支流",
    swimmingLayer: "底層與枯葉層",
    temperament: "大方外向 / 互動性強",
    diet: "短鯛顆粒、豐年蝦、微型紅蟲",
    substrate: "中細砂、枯葉造景",
    waterFlow: "弱緩水流",
    craftsmanTip: "背鰭如同鸚鵡鳳頭般巨大張揚，尾鰭佈滿烈焰般的橘紅棋盤格紋。適應水質廣泛，是進入南美短鯛殿堂的最佳先鋒。",
    citesStatus: "大師人工穩定育種品系",
    accentColor: "#f97316",
    badge: "烈焰鳳頭鸚鵡大尾",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短鯛", "霸王", "超紅尾", "耐養強健"]
  },
  {
    id: "cich-03",
    code: "RAMIREZI",
    name: "荷蘭鳳凰 (短鯛之冠)",
    enName: "German Blue Ram",
    sciName: "Mikrogeophagus ramirezi",
    category: "cichlids",
    categoryLabel: "南美慈鯛",
    difficulty: 2,
    tempMin: 26,
    tempMax: 30,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 5.5,
    origin: "委內瑞拉與哥倫比亞奧里諾科河流域",
    swimmingLayer: "中底層巡弋",
    temperament: "成對和諧 / 親代護卵",
    diet: "微細顆粒餌料、豐年蝦無節幼體",
    substrate: "細白沙、平滑扁平鵝卵石 (產卵用)",
    waterFlow: "溫和無衝擊水流",
    craftsmanTip: "身披電光藍、暖鵝黃與紫羅蘭漸層，黑眼帶貫穿紅眼。對水溫要求稍高 (26~29°C)，成對後會共同清理石塊並親自看護稚魚。",
    citesStatus: "全球經典育種",
    accentColor: "#06b6d4",
    badge: "電光七彩寶石慈鯛",
    featured: false,
    image: "images/discus.jpg",
    tags: ["荷蘭鳳凰", "電光藍", "親代護幼", "寶石色澤"]
  },
  {
    id: "cich-04",
    code: "ANOMALA",
    name: "金眼短鯛",
    enName: "Golden Dwarf Cichlid",
    sciName: "Nannacara anomala",
    category: "cichlids",
    categoryLabel: "南美短鯛",
    difficulty: 1,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 12,
    sizeCm: 6.5,
    origin: "蓋亞那與蘇利南沿海低地河流",
    swimmingLayer: "底層與水草根部",
    temperament: "溫和平易 / 母魚帶仔兇猛",
    diet: "沉性碎顆粒、水蚤、紅蟲",
    substrate: "各類水族細砂",
    waterFlow: "微弱水流",
    craftsmanTip: "雄魚具備閃耀祖母綠與金黃金屬光澤的鱗片，雙眼如金色明燈。極度耐養且繁殖容易，是觀察短鯛親魚帶仔行為的絕佳教材。",
    citesStatus: "常規普及",
    accentColor: "#eab308",
    badge: "金色明眸祖母綠甲",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短鯛", "金眼", "超高耐受力", "入門神品"]
  },
  {
    id: "cich-05",
    code: "TRIFASCIATA",
    name: "三線短鯛 (藍三線)",
    enName: "Three-striped Apisto",
    sciName: "Apistogramma trifasciata",
    category: "cichlids",
    categoryLabel: "南美短鯛",
    difficulty: 2,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.8,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 5.5,
    origin: "巴拉圭河與瓜波雷河流域",
    swimmingLayer: "中下層",
    temperament: "公魚展鰭華麗",
    diet: "豐年蝦、冷凍水蚤、微細顆粒",
    substrate: "細緻天然砂",
    waterFlow: "柔和水流",
    craftsmanTip: "雄魚背鰭高聳如帆，體側貫穿三條清晰黑色條紋，雙腮與腹部閃耀冷豔電光水藍色，身型小巧卻氣場強大。",
    citesStatus: "人工與野生兼具",
    accentColor: "#38bdf8",
    badge: "電光冰藍三道戰紋",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短鯛", "三線", "冰藍金屬", "高背鰭"]
  },
  {
    id: "cich-06",
    code: "AGASSIZII",
    name: "阿卡西短鯛 (雙紅火焰尾)",
    enName: "Agassiz's Dwarf Cichlid",
    sciName: "Apistogramma agassizii",
    category: "cichlids",
    categoryLabel: "南美短鯛",
    difficulty: 2,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 1,
    ghMax: 6,
    sizeCm: 7.5,
    origin: "亞馬遜流域廣闊水域 (秘魯至巴西亞馬遜河口)",
    swimmingLayer: "底層至中層",
    temperament: "領域展示華美",
    diet: "小型沉性顆粒、豐年蝦、微細凍餌",
    substrate: "落葉層、細軟底砂",
    waterFlow: "平緩水流",
    craftsmanTip: "長矛狀的尖形尾鰭是阿卡西的靈魂印記。雙紅品系的尾鰭外緣如燃燒火焰般鮮紅，中央貫穿白色利刃，游動時如焰矛破浪。",
    citesStatus: "經典名品系",
    accentColor: "#ef4444",
    badge: "長矛火焰尖尾阿卡西",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短鯛", "長矛尾", "火焰紅", "經典"]
  },
  {
    id: "cich-07",
    code: "ALTISPINOSUS",
    name: "玻利維亞鳳凰",
    enName: "Bolivian Ram",
    sciName: "Mikrogeophagus altispinosus",
    category: "cichlids",
    categoryLabel: "南美慈鯛",
    difficulty: 1,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.5,
    phMax: 7.5,
    ghMin: 4,
    ghMax: 12,
    sizeCm: 8.0,
    origin: "玻利維亞與巴西瓜波雷河流域",
    swimmingLayer: "底層與中下層",
    temperament: "極度溫順 / 混養模範生",
    diet: "雜食性沉底顆粒、薄片、紅蟲",
    substrate: "各類河砂",
    waterFlow: "中等水流",
    craftsmanTip: "體型較荷蘭鳳凰更為厚實強健，對水質容忍度極高，尾鰭上下邊緣鑲有鮮明紅邊，性情溫和不咬其他小型燈魚。",
    citesStatus: "常態引進",
    accentColor: "#f59e0b",
    badge: "混養模範生厚實鳳凰",
    featured: false,
    image: "images/discus.jpg",
    tags: ["玻利維亞", "強健溫和", "草缸混養"]
  },
  {
    id: "cich-08",
    code: "DIPLOTAENIA",
    name: "秘魯二線短鯛 (雙帶短鯛)",
    enName: "Band-tail Dwarf Cichlid",
    sciName: "Apistogramma diplotaenia",
    category: "cichlids",
    categoryLabel: "南美短鯛",
    difficulty: 4,
    tempMin: 24,
    tempMax: 29,
    phMin: 4.5,
    phMax: 5.8,
    ghMin: 1,
    ghMax: 3,
    sizeCm: 5.0,
    origin: "巴西內格羅河上游黑水極軟水域",
    swimmingLayer: "中下層水草枯枝間",
    temperament: "敏捷警覺 / 身形流線",
    diet: "活體無節幼蟲、水蚤、極細粉餌",
    substrate: "極細弱酸性黑水砂泥",
    waterFlow: "極微緩流",
    craftsmanTip: "體型修長如梭，體側兩道平行黑線在尾柄處優雅交會，身披夢幻淡紫與粉藍金屬光澤，是極致黑水環境的稀有珍寶。",
    citesStatus: "內格羅河野生稀有限定",
    accentColor: "#c084fc",
    badge: "黑水極軟水流線雙帶",
    featured: false,
    image: "images/discus.jpg",
    tags: ["短鯛", "極軟黑水", "雙帶", "內格羅河"]
  },

  // ==========================================
  // GROUP 6: 精品燈魚、脂鯉與奇異珍稀 (Tetras & Exotics)
  // ==========================================
  {
    id: "tetra-01",
    code: "CARDINAL",
    name: "頂級野生寶蓮燈 (日光燈之王)",
    enName: "Cardinal Tetra",
    sciName: "Paracheirodon axelrodi",
    category: "tetras",
    categoryLabel: "精品脂鯉燈魚",
    difficulty: 2,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.0,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 5,
    sizeCm: 4.5,
    origin: "內格羅河與奧里諾科河流域 (Rio Negro / Orinoco)",
    swimmingLayer: "中層百尾大群游",
    temperament: "和平溫柔 / 極致群游性",
    diet: "微細薄片、小型無節幼蟲、粉末飼料",
    substrate: "水草底床、沉木黑水",
    waterFlow: "中弱平穩水流",
    craftsmanTip: "腹部全通紅的鮮艷紅帶貫穿至尾柄，背部電光藍綠色霓虹線璀璨奪目。在百尾大群游時，在沉木水草造景中宛如流動的銀河星海。",
    citesStatus: "季節性野生大宗檢疫",
    accentColor: "#ef4444",
    badge: "亞馬遜流動紅藍霓虹銀河",
    featured: false,
    image: "images/discus.jpg",
    tags: ["寶蓮燈", "群游之王", "草缸必備", "霓虹紅藍"]
  },
  {
    id: "tetra-02",
    code: "ROYAL-TETRA",
    name: "皇室紅蓮燈 (克里燈 / 帝王燈)",
    enName: "Royal Tetra / Emperor Tetra",
    sciName: "Inpaichthys kerri",
    category: "tetras",
    categoryLabel: "精品脂鯉燈魚",
    difficulty: 2,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 4.0,
    origin: "巴西阿里普阿南河流域 (Rio Aripuana)",
    swimmingLayer: "中層水域",
    temperament: "優雅靈動",
    diet: "小型顆粒、水蚤、浮游生物",
    substrate: "深色細砂與茂密水草",
    waterFlow: "中弱水流",
    craftsmanTip: "成熟雄魚全身散發如皇家紫水晶般的深邃紫藍金屬光澤，尾鰭中央延長形成微三叉尾，在柔和頂燈下展現尊貴皇室氣質。",
    citesStatus: "穩定人工與野生",
    accentColor: "#818cf8",
    badge: "皇家紫水晶微三叉尾",
    featured: false,
    image: "images/discus.jpg",
    tags: ["帝王燈", "紫水晶", "金屬藍紫", "優雅"]
  },
  {
    id: "tetra-03",
    code: "RUMMY-NOSE",
    name: "紅鼻剪刀 (水質活指標)",
    enName: "Rummy-nose Tetra",
    sciName: "Hemigrammus rhodostomus",
    category: "tetras",
    categoryLabel: "精品脂鯉燈魚",
    difficulty: 2,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 5.0,
    origin: "亞馬遜河下游與奧里諾科河流域",
    swimmingLayer: "中層高速巡游",
    temperament: "整齊劃一的群游巡邏隊",
    diet: "微粒飼料、薄片、小型凍餌",
    substrate: "細緻水草砂",
    waterFlow: "中等水流",
    craftsmanTip: "吻部如鮮紅草莓般紅艷，尾鰭黑白斑紋如剪刀般俐落。頭部紅斑濃烈程度直接反映魚缸水質狀況，是職人缸中最忠實的水質活指標。",
    citesStatus: "廣泛穩定供應",
    accentColor: "#f43f5e",
    badge: "水質活指標黑白剪刀尾",
    featured: false,
    image: "images/discus.jpg",
    tags: ["紅鼻剪刀", "水質指標", "俐落群游", "黑白尾"]
  },
  {
    id: "tetra-04",
    code: "BLACK-GHOST",
    name: "黑魔鬼 (羽毛刀魚 / 綠翡翠刀)",
    enName: "Black Ghost Knifefish",
    sciName: "Apteronotus albifrons",
    category: "tetras",
    categoryLabel: "奇異古代魚",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 4,
    ghMax: 12,
    sizeCm: 35.0,
    origin: "亞馬遜與奧里諾科河流域深水岩層",
    swimmingLayer: "全水層無重力倒游",
    temperament: "夜行神祕 / 自體弱電場導航",
    diet: "肉食顆粒、紅蟲、鮮蝦碎肉、小魚",
    substrate: "沉木洞穴、平滑底砂、透明亞克力管",
    waterFlow: "中等水流",
    craftsmanTip: "全身如天鵝絨黑夜，透過微弱電場感應周遭障礙。其腹鰭能自如向前、向後、甚至上下無重力懸浮滑行，宛如水下幽靈舞者。",
    citesStatus: "常態引進",
    accentColor: "#64748b",
    badge: "弱電場無重力幽靈倒游",
    featured: false,
    image: "images/discus.jpg",
    tags: ["黑魔鬼", "弱電感應", "羽毛刀", "無重力游姿"]
  },
  {
    id: "tetra-05",
    code: "LYRETAIL-KILLI",
    name: "藍眼白金蝴蝶鱂 (琴尾鱂)",
    enName: "Cape Lopez Lyretail",
    sciName: "Aphyosemion australe",
    category: "tetras",
    categoryLabel: "多年生卵生鱂魚",
    difficulty: 2,
    tempMin: 21,
    tempMax: 25,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 5.5,
    origin: "西非加彭與剛果沿海雨林低窪沼澤",
    swimmingLayer: "中上層水草叢",
    temperament: "溫雅沉靜 / 善跳躍 (需蓋)",
    diet: "活體豐年蝦、水蚤、細微沉水蟲料",
    substrate: "泥炭土、水草茂密缸底",
    waterFlow: "微弱無造浪",
    craftsmanTip: "琴弦般優雅拉長的尾鰭上下葉，配上如蝴蝶展翅般的胸鰭與藍光大眼。雄魚橙金底色上嵌滿酒紅斑點，是多年生鱂魚的永恆經典。",
    citesStatus: "人工大師純化血統",
    accentColor: "#f59e0b",
    badge: "西非加彭琴尾蝴蝶羽翼",
    featured: false,
    image: "images/discus.jpg",
    tags: ["鱂魚", "琴尾", "蝴蝶胸鰭", "西非原色"]
  },
  {
    id: "tetra-06",
    code: "CONGO-TETRA",
    name: "剛果燈 (剛果帝王脂鯉)",
    enName: "Congo Tetra",
    sciName: "Phenacogrammus interruptus",
    category: "tetras",
    categoryLabel: "精品脂鯉燈魚",
    difficulty: 2,
    tempMin: 23,
    tempMax: 27,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 12,
    sizeCm: 8.5,
    origin: "非洲剛果河流域 (Congo River Basin)",
    swimmingLayer: "中層開闊水域",
    temperament: "大方優雅 / 雄魚羽狀展尾",
    diet: "各類漂浮薄片、水生昆蟲幼蟲、肉食顆粒",
    substrate: "深色底砂與開闊游動空間",
    waterFlow: "中等水流",
    craftsmanTip: "大鱗片折射出彩虹般的七彩金屬霓光，成年雄魚背鰭與尾鰭中央如羽毛般伸展飄逸，在水草大缸中群游時氣勢磅礡。",
    citesStatus: "人工與野生兼具",
    accentColor: "#38bdf8",
    badge: "剛果河彩虹七彩羽毛鰭",
    featured: false,
    image: "images/discus.jpg",
    tags: ["剛果燈", "彩虹鱗片", "羽毛尾", "大體型燈魚"]
  },
  {
    id: "tetra-07",
    code: "EMBER-TETRA",
    name: "噴火燈 (紅蓮微燈)",
    enName: "Ember Tetra",
    sciName: "Hyphessobrycon amandae",
    category: "tetras",
    categoryLabel: "精品脂鯉燈魚",
    difficulty: 1,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 2.0,
    origin: "巴西阿拉瓜亞河流域 (Rio Araguaia)",
    swimmingLayer: "中層水草茂密區",
    temperament: "小巧溫馴 / 群游緊湊",
    diet: "微米級微粉粒、微型水蚤",
    substrate: "水草泥床",
    waterFlow: "微弱水流",
    craftsmanTip: "僅 2 公分的微型瑰寶，通體透亮如果凍般的熾熱純橘紅色。在濃密綠色水草造景缸中，宛如點點燃燒的跳動火星。",
    citesStatus: "常規穩定人工與野生",
    accentColor: "#f97316",
    badge: "2cm 水草綠叢跳動火星",
    featured: false,
    image: "images/discus.jpg",
    tags: ["噴火燈", "微型燈魚", "草缸絕配", "果凍橘紅"]
  }
];

if (typeof window !== 'undefined') {
  window.SPECIES_DATA = SPECIES_DATA;
}
