/**
 * 海洋職人 (Ocean Craftsman) - 50種不重複珍稀魚種百科資料庫
 * 完全不重複，包含鼠魚系列深度專題、旗艦大師典藏、南美短鯛與精品脂鯉
 */

const SPECIES_DATA = [
  // ==========================================
  // GROUP 1: 鼠魚系列 - 長吻與高身珍稀類 (CW/Scleromystax)
  // ==========================================
  {
    id: "cory-01",
    code: "CW028",
    name: "帝王鼠",
    enName: "Imperial Corydoras",
    sciName: "Corydoras sp. CW028",
    category: "corydoras",
    categoryLabel: "長吻鼠魚",
    difficulty: 4,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 7.5,
    origin: "巴西亞馬遜黑水流域 (Rio Negro)",
    swimmingLayer: "底層水域 (Benthic)",
    temperament: "溫順沉穩 / 宜 5+ 群養",
    diet: "沉底肉食薄片、冷凍赤蟲、微細無脊椎動物",
    substrate: "極細純淨天然河砂 (防鬍鬚磨損)",
    waterFlow: "中等水流 / 超高溶氧",
    craftsmanTip: "帝王鼠吻部極長，對硝酸鹽及底砂細菌極度敏感。建議配置強力培菌系統與每週定期底砂虹吸。",
    citesStatus: "野生進口檢疫 / 珍稀典藏",
    accentColor: "#f5b942",
    badge: "CW028 典藏長吻",
    featured: false,
    image: "images/29. (C. imperator).jpg",
    tags: ["長吻", "黑水流域", "高溶氧喜好", "CW編號"]
  },
  {
    id: "cory-02",
    code: "CW051",
    name: "超級帝王鼠",
    enName: "Super Imperial Cory",
    sciName: "Corydoras sp. CW051",
    category: "corydoras",
    categoryLabel: "長吻鼠魚",
    difficulty: 5,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 6,
    sizeCm: 8.5,
    origin: "巴西內格羅河上游支流 (Upper Rio Negro)",
    swimmingLayer: "底層水域",
    temperament: "害羞沉著 / 愛陰暗處",
    diet: "活體豐年蝦、冷凍絲蚯蚓、高階沉底肉食錠",
    substrate: "超細圓潤矽砂 (粒徑 < 0.5mm)",
    waterFlow: "低至中等緩流",
    craftsmanTip: "背部具備如墨線般分明的粗黑條紋與高聳背鰭，需維持低 TDS (< 80 ppm) 與豐富沉木遮蔽物。",
    citesStatus: "高單價珍品 / 野生極稀少",
    accentColor: "#f5b942",
    badge: "CW051 夢幻逸品",
    featured: false,
    image: "images/46. (C. parallelus).jpg",
    tags: ["長吻", "大師級", "低硬度", "極稀珍品"]
  },
  {
    id: "cory-03",
    code: "SYCHRI",
    name: "撒旦長吻鼠",
    enName: "Sychr's Corydoras",
    sciName: "Corydoras sychri",
    category: "corydoras",
    categoryLabel: "長吻鼠魚",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 6.0,
    origin: "秘魯納乃河 (Rio Nanay, Peru)",
    swimmingLayer: "底層水域",
    temperament: "溫和活躍 / 喜探索底質",
    diet: "沉底錠餌、冷凍赤蟲、微藻錠",
    substrate: "細緻中性砂",
    waterFlow: "中等水流",
    craftsmanTip: "經典長吻代表，具備白銀底色與黑斑眼帶。適應力較強，是進入長吻鼠領域的最佳基石品種。",
    citesStatus: "常規檢疫進口",
    accentColor: "#38bdf8",
    badge: "秘魯代表長吻",
    featured: false,
    image: "images/49. (C. sychri).jpg",
    tags: ["長吻", "秘魯水系", "經典品種"]
  },
  {
    id: "cory-04",
    code: "CW010-D",
    name: "黑金紅頭鼠",
    enName: "Duplicate Cory",
    sciName: "Corydoras duplicares",
    category: "corydoras",
    categoryLabel: "長吻/短吻過渡",
    difficulty: 3,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 5.5,
    origin: "巴西普魯斯河流域 (Upper Rio Purus)",
    swimmingLayer: "底層水域",
    temperament: "溫和活潑 / 喜群游",
    diet: "沉底肉食微粒、豐年蝦幼蟲",
    substrate: "超細河砂",
    waterFlow: "中等水流",
    craftsmanTip: "背部黑粗帶寬厚，頭頂橘紅色澤如寶石閃耀。水溫不宜超過 28°C，高溫容易造成體色褪淡。",
    citesStatus: "市場高人氣穩定進口",
    accentColor: "#f97316",
    badge: "金光橘頂",
    featured: false,
    image: "images/23.  (C. duplicareus).jpg",
    tags: ["橘頂", "高對比", "群游性佳"]
  },
  {
    id: "cory-05",
    code: "ADOLFOI",
    name: "阿道夫鼠",
    enName: "Adolfo's Corydoras",
    sciName: "Corydoras adolfoi",
    category: "corydoras",
    categoryLabel: "短吻金頂類",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.6,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 5.5,
    origin: "巴西內格羅河支流 (Upper Rio Negro)",
    swimmingLayer: "底層水域",
    temperament: "溫和 / 容易混養",
    diet: "高品質沉底紅蟲粒、無節幼體",
    substrate: "天然極細河砂",
    waterFlow: "弱至中等水流",
    craftsmanTip: "與黑金紅頭極為相似，但阿道夫背部黑線較細緻精煉。水質維持弱酸性時頭頂橘斑更顯耀眼。",
    citesStatus: "常規引進",
    accentColor: "#f97316",
    badge: "經典金頂",
    featured: false,
    image: "images/22. (C. adolfoi).jpg",
    tags: ["金頂", "經典鼠魚", "黑水生境"]
  },
  {
    id: "cory-06",
    code: "BARBATUS",
    name: "高身蝙蝠鼠",
    enName: "Bearded Corydoras",
    sciName: "Scleromystax barbatus",
    category: "corydoras",
    categoryLabel: "Scleromystax 巨型類",
    difficulty: 4,
    tempMin: 18,
    tempMax: 24,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 4,
    ghMax: 10,
    sizeCm: 10.0,
    origin: "巴西東南部沿海溪流 (Coastal Streams of Brazil)",
    swimmingLayer: "底層水域",
    temperament: "雄魚具強烈領域感 / 體型威武",
    diet: "沉底高蛋白肉食錠、活體絲蚯蚓",
    substrate: "冷涼清澈粗細混砂",
    waterFlow: "強勁造浪水流 / 極高溶氧",
    craftsmanTip: "屬於低溫冷水型鼠魚，夏季務必配備冷水機降溫（< 24°C），成熟雄魚臉頰兩側具鬃毛狀倒刺。",
    citesStatus: "產地保護珍稀物種",
    accentColor: "#38bdf8",
    badge: "低溫王者 10cm",
    featured: false,
    image: "images/25.  (C. nattereri).jpg",
    tags: ["冷水性", "巨型", "長鬍腮刷", "Scleromystax"]
  },
  {
    id: "cory-07",
    code: "PRIONOTOS",
    name: "長吻蝙蝠鼠",
    enName: "Prionotos Cory",
    sciName: "Scleromystax prionotos",
    category: "corydoras",
    categoryLabel: "Scleromystax 長吻類",
    difficulty: 4,
    tempMin: 19,
    tempMax: 24,
    phMin: 6.2,
    phMax: 7.4,
    ghMin: 3,
    ghMax: 9,
    sizeCm: 8.5,
    origin: "巴西大西洋雨林溪流 (Atlantic Forest)",
    swimmingLayer: "底層水域",
    temperament: "活潑略帶領域性",
    diet: "沉底活餌、甲殼類微粒",
    substrate: "圓滑鵝卵石配細砂",
    waterFlow: "強烈溪流",
    craftsmanTip: "喜愛逆流衝浪，體側帶有斑駁幾何暗紋。飼養需確保充足水流動能與低水溫環境。",
    citesStatus: "野生偶有輸入",
    accentColor: "#38bdf8",
    badge: "雨林溪流長吻",
    featured: false,
    image: "images/34. (C. diplopterus).jpg",
    tags: ["長吻", "冷涼水系", "急流"]
  },
  {
    id: "cory-08",
    code: "SUP-SCHW",
    name: "超級舒瓦茲鼠",
    enName: "Super Schwarzi Cory",
    sciName: "Corydoras super schwarzi",
    category: "corydoras",
    categoryLabel: "高鰭斑紋類",
    difficulty: 4,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.6,
    phMax: 6.8,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 7.0,
    origin: "巴西普魯斯河流域 (Rio Purus)",
    swimmingLayer: "底層水域",
    temperament: "沉穩典雅 / 喜展示高聳背鰭",
    diet: "沉底錠餌、冷凍赤蟲、無脊椎動物",
    substrate: "極細白矽砂",
    waterFlow: "中等水流",
    craftsmanTip: "雄魚第一背鰭硬棘延伸如天線，筆直貫穿水體。體側粗黑線條如鐵軌般工整，水質越純淨線條越黑亮。",
    citesStatus: "玩家必備旗艦鼠魚",
    accentColor: "#f5b942",
    badge: "白色天線高鰭",
    featured: false,
    image: "images/6. (C. super schwartzi).jpg",
    tags: ["高鰭", "長天線", "普魯斯河", "觀賞極致"]
  },

  // ==========================================
  // GROUP 2: 鼠魚系列 - 短吻、圓吻與侏儒類
  // ==========================================
  {
    id: "cory-09",
    code: "PANDA",
    name: "熊貓鼠",
    enName: "Panda Corydoras",
    sciName: "Corydoras panda",
    category: "corydoras",
    categoryLabel: "短吻人氣類",
    difficulty: 1,
    tempMin: 20,
    tempMax: 25,
    phMin: 6.0,
    phMax: 7.4,
    ghMin: 2,
    ghMax: 10,
    sizeCm: 4.5,
    origin: "秘魯烏卡亞利河流域 (Rio Ucayali)",
    swimmingLayer: "底層水域",
    temperament: "極度溫和 / 活潑好動",
    diet: "一般沉底薄片、微顆粒、赤蟲",
    substrate: "中性細砂",
    waterFlow: "中等水流",
    craftsmanTip: "黑眼罩與尾柄黑斑酷似大熊貓。對水溫驟變較敏感，換水時需特別注意溫差控制在 1°C 以內。",
    citesStatus: "大量人工繁育 / 普及名種",
    accentColor: "#94a3b8",
    badge: "水族入門第一鼠",
    featured: false,
    image: "images/18. (C. panda).jpg",
    tags: ["短吻", "新手首選", "人氣王", "親人"]
  },
  {
    id: "cory-10",
    code: "STERBAI",
    name: "金翅珍珠鼠",
    enName: "Sterba's Corydoras",
    sciName: "Corydoras sterbai",
    category: "corydoras",
    categoryLabel: "短吻斑點類",
    difficulty: 1,
    tempMin: 24,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 12,
    sizeCm: 6.5,
    origin: "巴西瓜波雷河流域 (Rio Guapore)",
    swimmingLayer: "底層水域",
    temperament: "溫馴大方 / 易與七彩神仙混養",
    diet: "全能沉底飼料、冷凍豐年蝦",
    substrate: "細緻河砂",
    waterFlow: "中等水流",
    craftsmanTip: "胸鰭具備亮眼鮮橘色，滿身珍珠細斑。極少數能耐受 28~30°C 高溫的鼠魚，是七彩神仙缸的最佳清潔隊長。",
    citesStatus: "人工繁殖成熟",
    accentColor: "#f59e0b",
    badge: "耐高溫 29°C 首選",
    featured: false,
    image: "images/13.  (C. sterbai).jpg",
    tags: ["耐高溫", "珍珠點", "七彩搭檔", "入門強健"]
  },
  {
    id: "cory-11",
    code: "BURGESS",
    name: "紅頭鼠 (伯吉斯鼠)",
    enName: "Burgess's Corydoras",
    sciName: "Corydoras burgessi",
    category: "corydoras",
    categoryLabel: "短吻金頂類",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 5,
    sizeCm: 5.0,
    origin: "巴西內格羅河上游 (Rio Unini)",
    swimmingLayer: "底層水域",
    temperament: "溫和安靜",
    diet: "微細底棲沉餌、水蚤",
    substrate: "超細泥炭酸性砂",
    waterFlow: "緩流",
    craftsmanTip: "頭部具鮮明金橘色大斑塊，背鰭基部有一垂直粗黑斑。喜愛極軟弱酸性老水環境。",
    citesStatus: "野生採集檢疫",
    accentColor: "#f97316",
    badge: "黑水金橘頭",
    featured: false,
    image: "images/48.(iapoquensis).jpg",
    tags: ["短吻", "紅頭", "弱酸軟水"]
  },
  {
    id: "cory-12",
    code: "PYGMAEUS",
    name: "精靈鼠 (侏儒鼠)",
    enName: "Pygmy Corydoras",
    sciName: "Corydoras pygmaeus",
    category: "corydoras",
    categoryLabel: "侏儒懸浮類",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.2,
    phMax: 7.4,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 2.5,
    origin: "巴西馬代拉河流域 (Rio Madeira)",
    swimmingLayer: "中層至底層懸停游動",
    temperament: "群游性極強 / 適合 10+ 隻",
    diet: "粉狀微粒幼魚飼料、無節幼體",
    substrate: "水草泥或細砂",
    waterFlow: "平緩水流",
    craftsmanTip: "體長僅 2.5 cm，不只在底層爬行，更常成群懸停於水草葉片上。極度適合奈米水草造景缸。",
    citesStatus: "人工量產穩定",
    accentColor: "#10b981",
    badge: "2.5cm 奈米精靈",
    featured: false,
    image: "images/15.(C. pygmaeus)].webp",
    tags: ["侏儒", "中層群游", "草缸絕配", "迷你"]
  },
  {
    id: "cory-13",
    code: "HASTATUS",
    name: "月光鼠",
    enName: "Dwarf Corydoras / Tail-spot Cory",
    sciName: "Corydoras hastatus",
    category: "corydoras",
    categoryLabel: "侏儒懸浮類",
    difficulty: 3,
    tempMin: 20,
    tempMax: 25,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 2.5,
    origin: "巴拉圭河與亞馬遜河流域",
    swimmingLayer: "中層水域懸停群游",
    temperament: "活潑成群 / 如同小型加拉辛",
    diet: "微細水蚤、小型輪蟲、微粉飼料",
    substrate: "細沙或莫絲草皮",
    waterFlow: "弱水流",
    craftsmanTip: "尾柄處有一顆黑白相間如月芒般的鑽石斑點。常像蜂鳥般在水中高頻拍翅懸停，視覺效果極具療癒感。",
    citesStatus: "精緻觀賞魚",
    accentColor: "#38bdf8",
    badge: "懸停蜂鳥鼠",
    featured: false,
    image: "images/14. (C. hastatus).jpg",
    tags: ["迷你", "懸停", "尾斑月光"]
  },
  {
    id: "cory-14",
    code: "HABROSUS",
    name: "娃娃鼠",
    enName: "Salt and Pepper Catfish",
    sciName: "Corydoras habrosus",
    category: "corydoras",
    categoryLabel: "侏儒底棲類",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 3.0,
    origin: "哥倫比亞與委內瑞拉奧里諾科河流域",
    swimmingLayer: "專注底層爬行",
    temperament: "溫和安分",
    diet: "小型沉底顆粒、微蟲",
    substrate: "極細河砂",
    waterFlow: "中等水流",
    craftsmanTip: "三大侏儒鼠中唯一保有傳統鼠魚『底層勤奮耕砂』特性的品種，黑白胡椒碎花紋理格外討喜。",
    citesStatus: "常規進口",
    accentColor: "#94a3b8",
    badge: "3cm 耕砂小能手",
    featured: false,
    image: "images/40. (C. kanei).jpg",
    tags: ["侏儒", "胡椒鹽", "勤奮耕砂"]
  },
  {
    id: "cory-15",
    code: "EQUES",
    name: "黑箭鼠 (紅橘黑箭)",
    enName: "Eques Cory",
    sciName: "Corydoras eques",
    category: "corydoras",
    categoryLabel: "圓吻深色類",
    difficulty: 4,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 5,
    sizeCm: 5.0,
    origin: "巴西亞馬遜河幹流上游 (Coari / Tefe)",
    swimmingLayer: "底層水域",
    temperament: "害羞沉穩 / 體色極具辨識度",
    diet: "活體絲蚯蚓、沉底肉食錠",
    substrate: "純淨極細黑水砂",
    waterFlow: "弱至中等水流",
    craftsmanTip: "全身覆蓋深黑藍金屬光澤，鰓蓋後方圍繞著一道如同烈焰領巾的鮮橘紅色斑塊，對水質硝酸鹽極為敏感。",
    citesStatus: "野生高階珍品",
    accentColor: "#ea580c",
    badge: "深海烈焰領巾",
    featured: false,
    image: "images/16.  (C. eques).jpg",
    tags: ["圓吻", "黑金深邃", "橘領巾"]
  },
  {
    id: "cory-16",
    code: "RABAUTI",
    name: "紅肚鼠 (拉氏鼠)",
    enName: "Rabaut's Corydoras",
    sciName: "Corydoras rabauti",
    category: "corydoras",
    categoryLabel: "圓吻雙色類",
    difficulty: 2,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 5.5,
    origin: "巴西雅普拉河與內格羅河流域",
    swimmingLayer: "底層水域",
    temperament: "溫和好動",
    diet: "一般沉底飼料、冷凍豐年蝦",
    substrate: "細緻河砂",
    waterFlow: "中等水流",
    craftsmanTip: "背部呈現鮮明銹橘紅色，從背鰭一路延伸至尾鰭有一條漸層粗黑條紋。幼魚階段全身覆蓋虎皮斑紋，極富變態趣味。",
    citesStatus: "常規引進",
    accentColor: "#f97316",
    badge: "紅背銹彩",
    featured: false,
    image: "images/38.  (C. arcuatus).jpg",
    tags: ["圓吻", "雙色漸層", "幼魚虎斑"]
  },
  {
    id: "cory-17",
    code: "VIRGINAE",
    name: "印第安鼠 (白狐狸鼠)",
    enName: "Roundhead Indian Cory",
    sciName: "Corydoras virginae",
    category: "corydoras",
    categoryLabel: "圓吻斑紋類",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 5.5,
    origin: "秘魯烏卡亞利河流域",
    swimmingLayer: "底層水域",
    temperament: "溫和親人",
    diet: "各類沉底錠餌、紅蟲",
    substrate: "中性河砂",
    waterFlow: "中等水流",
    craftsmanTip: "白色純淨底色搭配如同印第安羽冠般的粗黑眼帶與斜向背紋，適應力強且極具活潑探索欲。",
    citesStatus: "常規進口",
    accentColor: "#64748b",
    badge: "羽冠面具印第安",
    featured: false,
    image: "images/44. (C. leucomelas).jpg",
    tags: ["圓吻", "印第安黑帶", "強健"]
  },
  {
    id: "cory-18",
    code: "BLACK-VEN",
    name: "委內瑞拉黑鼠",
    enName: "Black Venezuela Cory",
    sciName: "Corydoras schultzei 'Black'",
    category: "corydoras",
    categoryLabel: "純色突變類",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 5.5,
    origin: "歐洲繁育品系 (原種源自德國/委內瑞拉)",
    swimmingLayer: "底層水域",
    temperament: "溫和活躍 / 搶食迅速",
    diet: "沉底肉食顆粒、各類人工飼料",
    substrate: "淺色細白砂 (強化黑白視覺對比)",
    waterFlow: "中等水流",
    craftsmanTip: "通體呈現如同黑曜石般的深邃墨黑，腹鰭與尾鰭帶有些微深紅褐色光澤。在白砂缸中具備極強視覺衝擊力。",
    citesStatus: "人工品系穩定",
    accentColor: "#1e293b",
    badge: "黑曜石墨黑純種",
    featured: false,
    image: "images/10. (c. schultzei black).jpg",
    tags: ["純黑", "黑曜石", "人工培育", "高對比"]
  },

  // ==========================================
  // GROUP 3: 鼠魚系列 - 雷射與翡翠巨斑專題
  // ==========================================
  {
    id: "cory-19",
    code: "CW010",
    name: "黃金雷射鼠",
    enName: "Gold Laser Cory",
    sciName: "Corydoras sp. CW010",
    category: "corydoras",
    categoryLabel: "雷射反光類",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 6.0,
    origin: "秘魯烏卡亞利河流域 (Rio Ucayali, Peru)",
    swimmingLayer: "底層水域",
    temperament: "成群游動 / 喜弱光照",
    diet: "沉底高品質薄片、微細肉食微粒",
    substrate: "暗色細砂或泥炭底砂",
    waterFlow: "中等水流",
    craftsmanTip: "體側中央鑲嵌一條如霓虹燈管般刺眼的 24K 金色金屬反光色帶。適度調暗燈光更顯其雷射折射效果。",
    citesStatus: "野生限量輸入",
    accentColor: "#eab308",
    badge: "24K 金屬霓虹雷射",
    featured: false,
    image: "images/31. (C. gold stripe).png",
    tags: ["黃金雷射", "霓虹光", "秘魯", "CW010"]
  },
  {
    id: "cory-20",
    code: "CW009",
    name: "綠線雷射鼠",
    enName: "Green Laser Cory",
    sciName: "Corydoras sp. CW009",
    category: "corydoras",
    categoryLabel: "雷射反光類",
    difficulty: 3,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 6.0,
    origin: "秘魯烏卡亞利河流域支流",
    swimmingLayer: "底層水域",
    temperament: "溫和活躍",
    diet: "沉底錠餌、冷凍豐年蝦",
    substrate: "深色細砂",
    waterFlow: "中等水流",
    craftsmanTip: "具備鮮明亮麗的翠綠色螢光金屬反光帶，背部墨黑深沉。在 LED 植物水草燈下會散發極致翡翠冷光。",
    citesStatus: "野生採集進口",
    accentColor: "#10b981",
    badge: "翠綠螢光雷射",
    featured: false,
    image: "images/32.(C. green line).jpg",
    tags: ["綠雷射", "翡翠光", "CW009"]
  },
  {
    id: "cory-21",
    code: "CW023",
    name: "橘紅雷射鼠",
    enName: "Orange Laser Cory",
    sciName: "Corydoras sp. CW023",
    category: "corydoras",
    categoryLabel: "雷射反光類",
    difficulty: 4,
    tempMin: 22,
    tempMax: 26,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 6.5,
    origin: "秘魯東部亞馬遜支流",
    swimmingLayer: "底層水域",
    temperament: "沉靜害羞",
    diet: "高品質活餌、沉底肉食錠",
    substrate: "極細天然矽砂",
    waterFlow: "緩流至中等",
    craftsmanTip: "雷射家族中最為罕見的品種，體側帶有熔岩般熾熱的橘紅色金屬光帶。需維持極佳水質防止體色暗淡。",
    citesStatus: "夢幻珍品進口",
    accentColor: "#f97316",
    badge: "熔岩橘紅雷射",
    featured: false,
    image: "images/8.  (C. colombianus).jpg",
    tags: ["橘雷射", "熔岩光", "CW023", "極珍稀"]
  },
  {
    id: "cory-22",
    code: "BROCHIS-01",
    name: "綠面翡翠鼠 (巨型青銅鼠)",
    enName: "Emerald Catfish",
    sciName: "Brochis splendens",
    category: "corydoras",
    categoryLabel: "Brochis 翡翠類",
    difficulty: 2,
    tempMin: 22,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 4,
    ghMax: 12,
    sizeCm: 8.5,
    origin: "亞馬遜流域廣布 (巴西/秘魯/厄瓜多)",
    swimmingLayer: "底層至中下層",
    temperament: "極度強健大方 / 搶食兇悍",
    diet: "各類沉底錠餌、高蛋白飼料",
    substrate: "一般水族砂皆可",
    waterFlow: "中等水流",
    craftsmanTip: "背鰭鰭條多達 10~12 根（普通鼠魚僅 7~8 根）。全身覆蓋如翡翠綠寶石般的厚實骨板，防禦力驚人且容易飼養。",
    citesStatus: "市場長青強健品種",
    accentColor: "#059669",
    badge: "翡翠裝甲 8.5cm",
    featured: false,
    image: "images/12. (C. splendens).jpg",
    tags: ["Brochis", "翡翠光", "巨型", "強健首選"]
  },
  {
    id: "cory-23",
    code: "BROCHIS-02",
    name: "巨型長吻巨斑青銅鼠",
    enName: "Hog-nosed Brochis",
    sciName: "Brochis multiradiatus",
    category: "corydoras",
    categoryLabel: "Brochis 長吻類",
    difficulty: 4,
    tempMin: 21,
    tempMax: 25,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 10.0,
    origin: "厄瓜多與秘魯亞馬遜上游支流 (Rio Napo)",
    swimmingLayer: "底層水域",
    temperament: "雄渾沉穩",
    diet: "高能量肉食錠、冷凍赤蟲",
    substrate: "圓滑天然細河砂",
    waterFlow: "強勁溶氧水流",
    craftsmanTip: "吻部明顯向下彎曲如豬吻狀，體型可達 10 cm 以上，是 Brochis 屬中的頂級巨無霸，需配置 3 尺以上大缸。",
    citesStatus: "野生珍稀採集",
    accentColor: "#0d9488",
    badge: "10cm 巨獸長吻",
    featured: false,
    image: "images/9. (C. aeneus).jpg",
    tags: ["Brochis", "長吻巨型", "豬吻", "珍稀"]
  },
  {
    id: "cory-24",
    code: "BOESEMANI",
    name: "國王黑金鼠 (博氏鼠)",
    enName: "Boeseman's Corydoras",
    sciName: "Corydoras boesemani",
    category: "corydoras",
    categoryLabel: "蘇利南珍稀類",
    difficulty: 4,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 5.5,
    origin: "蘇利南內陸流域 (Suriname Basin)",
    swimmingLayer: "底層水域",
    temperament: "溫文儒雅",
    diet: "沉底微粉薄片、小型活餌",
    substrate: "極細純白矽砂",
    waterFlow: "中等水流",
    craftsmanTip: "來自蘇利南的珍稀夢幻物種，體側背部有一塊圓潤大黑斑，尾柄具兩道平行墨黑斑紋，血統純正優雅。",
    citesStatus: "蘇利南國家配額輸出",
    accentColor: "#ca8a04",
    badge: "蘇利南黑金國王",
    featured: false,
    image: "images/47.(C. pulcher).jpg",
    tags: ["蘇利南", "黑金斑", "國王鼠", "極珍貴"]
  },
  {
    id: "cory-25",
    code: "GOSSEI",
    name: "金珍珠鼠 (高斯鼠)",
    enName: "Gosse's Corydoras",
    sciName: "Corydoras gossei",
    category: "corydoras",
    categoryLabel: "金翅斑紋類",
    difficulty: 3,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 6.0,
    origin: "巴西馬代拉河流域 (Rio Mamore / Madeira)",
    swimmingLayer: "底層水域",
    temperament: "沉著溫和",
    diet: "沉底肉食微粒、冷凍赤蟲",
    substrate: "超細河砂",
    waterFlow: "中等水流",
    craftsmanTip: "背鰭前緣與胸鰭硬棘呈現如同金黃烤漆般的亮麗色彩，體背深黑並點綴微細白斑，對底質清潔度要求極高。",
    citesStatus: "野生常規輸入",
    accentColor: "#f59e0b",
    badge: "黃金背刺高斯",
    featured: false,
    image: "images/41. (C. gossei).jpg",
    tags: ["金翅", "黑水生境", "巴西經典"]
  },
  {
    id: "cory-26",
    code: "PANTANAL",
    name: "巨無霸網球鼠 (潘塔納爾鼠)",
    enName: "Pantanal Catfish",
    sciName: "Corydoras pantanalensis",
    category: "corydoras",
    categoryLabel: "婚色變異巨型類",
    difficulty: 5,
    tempMin: 22,
    tempMax: 27,
    phMin: 6.2,
    phMax: 7.6,
    ghMin: 4,
    ghMax: 12,
    sizeCm: 8.5,
    origin: "巴西潘塔納爾大濕地 (Pantanal Wetland)",
    swimmingLayer: "底層水域",
    temperament: "發情期雄魚具強烈爭鬥展示行為",
    diet: "大型肉食沉底錠、活體絲蚯蚓",
    substrate: "中細混合天然砂",
    waterFlow: "強大水循環造流",
    craftsmanTip: "鼠魚界的變形金剛！繁殖發情季節雄魚全身會由平凡灰斑轉變為如同黑色蕾絲網球般的繁複幾何黑網，極具震撼力。",
    citesStatus: "高單價旗艦物種",
    accentColor: "#6366f1",
    badge: "發情變身 8.5cm 巨獸",
    featured: false,
    image: "images/21. (C. reticulatus).jpg",
    tags: ["婚色變形", "潘塔納爾", "大師級", "幾何黑網"]
  },
  {
    id: "cory-27",
    code: "TRILINEATUS",
    name: "白金豹鼠 (三線豹鼠)",
    enName: "Three-stripe Corydoras",
    sciName: "Corydoras trilineatus",
    category: "corydoras",
    categoryLabel: "豹紋迷宮類",
    difficulty: 2,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.4,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 5.5,
    origin: "亞馬遜河中上游支流 (秘魯/巴西)",
    swimmingLayer: "底層水域",
    temperament: "活潑成群",
    diet: "各類人工沉料、無節幼體",
    substrate: "細緻河砂",
    waterFlow: "中等水流",
    craftsmanTip: "常被誤認為真茱莉豹鼠 (C. julii)，三線豹頭頂呈現網狀迷宮紋而非純圓點。體側三道黑線貫穿，花紋華麗耐看。",
    citesStatus: "常規穩定引進",
    accentColor: "#94a3b8",
    badge: "迷宮豹紋貫穿",
    featured: false,
    image: "images/19.  (C. trilineatus).jpg",
    tags: ["三線豹", "迷宮紋", "經典花紋"]
  },
  {
    id: "cory-28",
    code: "ROBUSTUS",
    name: "皇室巨斑鼠 (羅伯斯鼠)",
    enName: "Robust Corydoras",
    sciName: "Corydoras robustus",
    category: "corydoras",
    categoryLabel: "巨型長吻類",
    difficulty: 5,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 5,
    sizeCm: 9.5,
    origin: "巴西普魯斯河流域 (Rio Purus)",
    swimmingLayer: "底層水域",
    temperament: "雄偉威嚴 / 動作敏捷",
    diet: "沉底高蛋白生鮮肉餌、大型肉食錠",
    substrate: "極細純天然河砂",
    waterFlow: "強大溶氧",
    craftsmanTip: "長吻鼠魚中的巨型泰坦，體長可逼近 10 cm！背鰭硬棘如長戟高聳，對水質酸化軟水有極高要求。",
    citesStatus: "極稀少野生輸入",
    accentColor: "#e11d48",
    badge: "9.5cm 長戟泰坦",
    featured: false,
    image: "images/33. (C. robineae).jpg",
    tags: ["長吻泰坦", "普魯斯河", "大師級", "長戟背鰭"]
  },

  // ==========================================
  // GROUP 4: 職人大師旗艦名品 (Master Flagships)
  // ==========================================
  {
    id: "flag-01",
    code: "RED-AROWANA",
    name: "頂級特級亞洲紅龍",
    enName: "Super Red Asian Arowana",
    sciName: "Scleropages formosus",
    category: "flagship",
    categoryLabel: "大師旗艦魚種",
    difficulty: 5,
    tempMin: 26,
    tempMax: 30,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 65.0,
    origin: "印尼加里曼丹卡普阿斯河流域 (Kapuas River)",
    swimmingLayer: "上層水域 (Pelagic / Surface)",
    temperament: "王者霸氣 / 具高度地盤意識",
    diet: "特級冷凍鮮蝦、活體大麥蟲、泥鰍、專用浮水肉食條",
    substrate: "裸缸 (Bare-bottom) 便於高效排污",
    waterFlow: "平穩緩流搭配強力滴流過濾與 UV 殺菌系統",
    craftsmanTip: "亞洲紅龍發色需結合 6500K 太陽光譜燈具與適度黑水環境。水質維持 pH 6.5，換水時需特別預防掉眼與縮鰭。",
    citesStatus: "CITES 附錄 I (附晶片身分證書)",
    accentColor: "#ef4444",
    badge: "CITES 附錄 I 王者",
    featured: true,
    image: "images/arowana.jpg",
    tags: ["龍魚", "頂級霸主", "上層游姿", "晶片驗證"]
  },
  {
    id: "flag-02",
    code: "HECKEL-DISCUS",
    name: "黑格爾七彩神仙 (野生黑格爾)",
    enName: "Heckel Wild Discus",
    sciName: "Symphysodon discus 'Heckel'",
    category: "flagship",
    categoryLabel: "大師旗艦魚種",
    difficulty: 5,
    tempMin: 28,
    tempMax: 31,
    phMin: 4.8,
    phMax: 6.2,
    ghMin: 1,
    ghMax: 3,
    sizeCm: 18.0,
    origin: "巴西尼格羅河流域 (Rio Negro / Rio Branco)",
    swimmingLayer: "中層水域 (Mid-water)",
    temperament: "優雅敏感 / 宜 6+ 群養",
    diet: "頂級牛心漢堡、冷凍赤蟲、白金微粒",
    substrate: "極細白矽砂或黑水沉木林造景",
    waterFlow: "弱水流 / 極高生化過濾量",
    craftsmanTip: "野生七彩之皇。第 5 條暗黑棟線粗厚分明。必須維持超低 TDS (< 50 ppm) 與弱酸黑水，水溫需長年保持 29°C 以上。",
    citesStatus: "野生進口檢疫成體",
    accentColor: "#06b6d4",
    badge: "熱帶魚之后",
    featured: true,
    image: "images/discus.jpg",
    tags: ["七彩神仙", "黑格爾", "黑水生境", "大師級"]
  },
  {
    id: "flag-03",
    code: "CROWN-BETTA",
    name: "皇家藍冠尾鬥魚 (王者之冠)",
    enName: "Royal Blue Crowntail Betta",
    sciName: "Betta splendens 'Crowntail'",
    category: "flagship",
    categoryLabel: "大師旗艦魚種",
    difficulty: 2,
    tempMin: 24,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.4,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 7.0,
    origin: "泰國湄公河流域人工培育品系",
    swimmingLayer: "全水域 / 喜近水面築泡巢",
    temperament: "單獨飼養 / 照鏡展鰭展示霸氣",
    diet: "高蛋白鬥魚專用肉食微粒、冷凍赤蟲、無節幼體",
    substrate: "欖仁葉底床 / 沉木水草造景",
    waterFlow: "極微弱水流 (避免吹散鰭針)",
    craftsmanTip: "鰭膜退縮率達 66% 以上，呈現出如同皇冠般分明的放射狀針骨。每日需進行 10 分鐘對鏡展鰭訓練以強化骨架開度。",
    citesStatus: "人工培育名品",
    accentColor: "#3b82f6",
    badge: "皇冠針芒 180°",
    featured: true,
    image: "images/betta.jpg",
    tags: ["冠尾鬥魚", "展鰭展示", "迷鰓魚", "皇家藍"]
  },
  {
    id: "flag-04",
    code: "L046-ZEBRA",
    name: "帝王斑馬異型 (L046)",
    enName: "Imperial Zebra Pleco (L046)",
    sciName: "Hypancistrus zebra",
    category: "flagship",
    categoryLabel: "大師旗艦魚種",
    difficulty: 4,
    tempMin: 28,
    tempMax: 31,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 9.5,
    origin: "巴西欣古河流域大拐彎 (Rio Xingu, Altamira)",
    swimmingLayer: "底層洞穴 (Cave Dweller)",
    temperament: "害羞夜行 / 喜專屬陶罐躲藏",
    diet: "沉底高蛋白異型錠、冷凍豐年蝦、赤蟲",
    substrate: "深色玄武岩石塊與專用繁育陶罐",
    waterFlow: "強大溶氧暴氣 / 湍急造浪流",
    craftsmanTip: "白瓷般的底色鑲嵌如鋼筆勾勒出的墨黑幾何線條。欣古河原生環境高溫多氧，飼養需配置 28.5°C 以上溫控與高溶氧氣舉。",
    citesStatus: "CITES 附錄 III (野生禁止輸出 / 人工繁育)",
    accentColor: "#f8fafc",
    badge: "欣古河黑白鑽石",
    featured: true,
    image: "images/pleco.jpg",
    tags: ["異型魚", "L046", "欣古河", "黑白條紋"]
  },
  {
    id: "flag-05",
    code: "L014-SUNSHINE",
    name: "黃金達摩異型 (L014)",
    enName: "Sunshine Pleco (L014)",
    sciName: "Scobinancistrus aureatus",
    category: "flagship",
    categoryLabel: "大師旗艦魚種",
    difficulty: 3,
    tempMin: 26,
    tempMax: 30,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 30.0,
    origin: "巴西欣古河流域 (Rio Xingu)",
    swimmingLayer: "底層水域",
    temperament: "食量巨大 / 體型壯碩",
    diet: "底棲肉食沉糧、螺類、沉木植物纖維",
    substrate: "粗顆粒天然河石",
    waterFlow: "強勁急流 / 巨大排污過濾系統",
    craftsmanTip: "幼魚通體佈滿鮮黃色圓點，成魚胸鰭與尾鰭散發金黃陽光色澤。是肉食性大型異型的代表作，需配備強力排污過濾。",
    citesStatus: "野生進口檢疫",
    accentColor: "#eab308",
    badge: "欣古河黃金巨獸",
    featured: false,
    image: "images/pleco.jpg",
    tags: ["異型魚", "L014", "黃金陽光", "大型異型"]
  },
  {
    id: "flag-06",
    code: "PLATINUM-GUPPY",
    name: "白金全紅白子孔雀魚",
    enName: "Albino Full Red Platinum Guppy",
    sciName: "Poecilia reticulata 'Albino Full Red'",
    category: "flagship",
    categoryLabel: "大師旗艦魚種",
    difficulty: 2,
    tempMin: 22,
    tempMax: 27,
    phMin: 6.8,
    phMax: 7.8,
    ghMin: 6,
    ghMax: 15,
    sizeCm: 5.0,
    origin: "台灣大師級玩家精心育種純系",
    swimmingLayer: "中上層水域",
    temperament: "溫和活躍 / 繁殖力旺盛",
    diet: "高階孔雀魚微細顆粒、現孵豐年蝦幼蟲",
    substrate: "中性大磯砂或弱鹼性底質",
    waterFlow: "平緩緩流",
    craftsmanTip: "紅寶石般的眼球搭配胸腹部厚實白金金屬反光厚度，大背鰭如紅綢緞飄逸。需維持 GH 8~12 硬度以防止溶尾與夾尾。",
    citesStatus: "冠軍純系品系",
    accentColor: "#f43f5e",
    badge: "台灣冠軍育種系",
    featured: false,
    image: "images/guppy.jpg",
    tags: ["孔雀魚", "全紅白子", "白金厚度", "水草缸搭檔"]
  },
  {
    id: "flag-07",
    code: "BLACK-DIAMOND",
    name: "皇冠黑白魟魚 (黑鑽石魟)",
    enName: "Black Diamond Stingray",
    sciName: "Potamotrygon leopoldi",
    category: "flagship",
    categoryLabel: "大師旗艦魚種",
    difficulty: 5,
    tempMin: 26,
    tempMax: 30,
    phMin: 6.2,
    phMax: 7.4,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 50.0,
    origin: "巴西欣古河流域 (Rio Xingu)",
    swimmingLayer: "底層盤旋 (Benthic Glider)",
    temperament: "大型掠食者 / 體型震撼",
    diet: "活體小魚、鮮蝦、泥鰍、頂級魟魚沉底肉食糧",
    substrate: "超大空間無底砂或超細圓滑砂",
    waterFlow: "超大過濾水體 / 雙重滴流盒",
    craftsmanTip: "漆黑如夜空的體盤上點綴著如同星辰般耀眼的甜甜圈白斑。對水中氨氮與氯極度過敏，需 5 尺以上巨大水槽。",
    citesStatus: "CITES 附錄 II 管制物種",
    accentColor: "#1e293b",
    badge: "欣古星空黑鑽石",
    featured: false,
    image: "images/24. (C. venezuelanus black).jpg",
    tags: ["淡水魟魚", "黑鑽石", "欣古河", "大師旗艦"]
  },

  // ==========================================
  // GROUP 5: 南美短鯛殿堂 (Apistogramma Cichlids)
  // ==========================================
  {
    id: "cich-01",
    code: "BITAENIATA",
    name: "酋長短鯛 (雙線短鯛)",
    enName: "Bitaeniata Dwarf Cichlid",
    sciName: "Apistogramma bitaeniata",
    category: "cichlids",
    categoryLabel: "南美精緻短鯛",
    difficulty: 4,
    tempMin: 24,
    tempMax: 28,
    phMin: 5.0,
    phMax: 6.5,
    ghMin: 1,
    ghMax: 4,
    sizeCm: 7.0,
    origin: "秘魯至巴西亞馬遜黑水流域",
    swimmingLayer: "中下層 / 穿梭於沉木水草間",
    temperament: "雄魚具強烈展示欲 (Flaring) / 護幼天性",
    diet: "活體豐年蝦、冷凍水蚤、短鯛專用肉食薄片",
    substrate: "極細天然黑水砂配欖仁葉",
    waterFlow: "緩流至靜水",
    craftsmanTip: "背鰭琴弦狀拉高，尾鰭呈現上下延伸的雙琴尾。雄魚在弱酸極軟黑水中會散發耀眼金屬藍紫反光。",
    citesStatus: "野生進口檢疫",
    accentColor: "#a855f7",
    badge: "雙琴尾酋長",
    featured: false,
    image: "images/36. (C. similis).jpg",
    tags: ["短鯛", "酋長", "雙琴尾", "黑水生境"]
  },
  {
    id: "cich-02",
    code: "CACATUOIDES",
    name: "霸王短鯛 (三叉超紅尾)",
    enName: "Cockatoo Dwarf Cichlid",
    sciName: "Apistogramma cacatuoides",
    category: "cichlids",
    categoryLabel: "南美精緻短鯛",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 8.0,
    origin: "秘魯烏卡亞利河流域",
    swimmingLayer: "中下層水域",
    temperament: "雄壯自信 / 容易繁殖",
    diet: "各類沉底薄片、赤蟲、豐年蝦",
    substrate: "天然水草砂配陶罐洞穴",
    waterFlow: "中等緩流",
    craftsmanTip: "如同鳳頭鸚鵡般高聳展開的前背鰭棘刺，配上火紅花紋尾鰭。適應水質廣泛，是短鯛愛好者的最佳入門名品。",
    citesStatus: "人工培育成熟",
    accentColor: "#ef4444",
    badge: "鳳頭冠羽超紅尾",
    featured: false,
    image: "images/45. (C. guapore).jpg",
    tags: ["霸王短鯛", "超紅尾", "耐水質廣", "強健"]
  },
  {
    id: "cich-03",
    code: "RAMIREZI",
    name: "荷蘭鳳凰 (短鯛之冠)",
    enName: "German / Dutch Blue Ram",
    sciName: "Mikrogeophagus ramirezi",
    category: "cichlids",
    categoryLabel: "南美精緻短鯛",
    difficulty: 3,
    tempMin: 26,
    tempMax: 30,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 5.5,
    origin: "委內瑞拉與哥倫比亞奧里諾科平原 (Llanos)",
    swimmingLayer: "中底層活動",
    temperament: "成對恩愛 / 護卵忠誠",
    diet: "冷凍微蟲、高品質微粒飼料",
    substrate: "細緻矽砂搭配平滑產卵石",
    waterFlow: "弱水流",
    craftsmanTip: "全身閃耀著孔雀石綠、金黃、亮藍與腹部粉紅的斑斕色彩。喜歡 27°C 以上溫暖水溫與極潔淨無硝酸鹽環境。",
    citesStatus: "人工品系繁育",
    accentColor: "#06b6d4",
    badge: "五彩斑斕短鯛之后",
    featured: false,
    image: "images/20.  (C. davidandseni).jpg",
    tags: ["荷蘭鳳凰", "彩虹色彩", "高溫軟水", "成對產卵"]
  },
  {
    id: "cich-04",
    code: "ANOMALA",
    name: "金眼短鯛",
    enName: "Golden Dwarf Cichlid",
    sciName: "Nannacara anomala",
    category: "cichlids",
    categoryLabel: "南美精緻短鯛",
    difficulty: 1,
    tempMin: 22,
    tempMax: 26,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 12,
    sizeCm: 6.5,
    origin: "蓋亞那與蘇利南沿海河流",
    swimmingLayer: "底層與水草根部",
    temperament: "母魚帶子時防禦力極強",
    diet: "一般人工顆粒、小型生餌",
    substrate: "水草底床配密植默絲",
    waterFlow: "平緩水流",
    craftsmanTip: "雄魚體側呈現金屬祖母綠反光，雌魚繁殖期會轉變為如同棋盤格般的黑白強烈花紋，生命力極為頑強。",
    citesStatus: "常規穩定引進",
    accentColor: "#10b981",
    badge: "祖母綠金眼小鋼炮",
    featured: false,
    image: "images/28. (C. aeneus albino).jpg",
    tags: ["金眼短鯛", "祖母綠", "超強適應力"]
  },
  {
    id: "cich-05",
    code: "TRIFASCIATA",
    name: "三線短鯛 (藍三線)",
    enName: "Three-stripe Dwarf Cichlid",
    sciName: "Apistogramma trifasciata",
    category: "cichlids",
    categoryLabel: "南美精緻短鯛",
    difficulty: 3,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.8,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 5.5,
    origin: "巴拉圭河與瓜波雷河流域",
    swimmingLayer: "中下層水草叢",
    temperament: "雄魚展鰭氣勢凌人",
    diet: "豐年蝦幼蟲、微顆粒沉餌",
    substrate: "細緻河砂配沉木",
    waterFlow: "弱水流",
    craftsmanTip: "前背鰭鰭條極長且散發亮麗天空藍金屬色澤，三條橫向黑色線條清晰標誌，是南美短鯛的經典代表。",
    citesStatus: "常規引進",
    accentColor: "#38bdf8",
    badge: "天空藍高背鰭",
    featured: false,
    image: "images/11. (C. super haraldschultzi).jpg",
    tags: ["三線短鯛", "金屬藍", "經典品種"]
  },
  {
    id: "cich-06",
    code: "AGASSIZII",
    name: "阿卡西短鯛 (雙紅火焰尾)",
    enName: "Agassiz's Dwarf Cichlid",
    sciName: "Apistogramma agassizii",
    category: "cichlids",
    categoryLabel: "南美精緻短鯛",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 5.0,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 5,
    sizeCm: 7.5,
    origin: "亞馬遜河流域 (巴西/秘魯廣泛分佈)",
    swimmingLayer: "中下層水域",
    temperament: "雄魚具強烈領地美感展示",
    diet: "冷凍赤蟲、無節幼體、高品質沉粒",
    substrate: "酸性黑水砂",
    waterFlow: "緩流",
    craftsmanTip: "矛狀尾鰭（尖尾）是其最大特徵，雙紅火焰品系尾鰭外緣被烈火般的橙紅包覆，中央散發電光藍。",
    citesStatus: "野生與人工培育皆有",
    accentColor: "#f43f5e",
    badge: "火焰矛尾阿卡西",
    featured: false,
    image: "images/4. (C. seussi).jpg",
    tags: ["阿卡西", "矛尾", "火焰紅", "經典短鯛"]
  },
  {
    id: "cich-07",
    code: "ALTISPINOSUS",
    name: "玻利維亞鳳凰",
    enName: "Bolivian Ram",
    sciName: "Mikrogeophagus altispinosus",
    category: "cichlids",
    categoryLabel: "南美精緻短鯛",
    difficulty: 2,
    tempMin: 23,
    tempMax: 27,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 10,
    sizeCm: 8.0,
    origin: "玻利維亞與巴西馬莫雷河流域",
    swimmingLayer: "底層與中層",
    temperament: "溫和無攻擊性 / 適合混養",
    diet: "各類雜食沉糧、赤蟲、薄片",
    substrate: "天然中性河砂",
    waterFlow: "中等水流",
    craftsmanTip: "相比荷蘭鳳凰更為強健耐養，尾鰭上下邊緣帶有亮眼紅邊，體型較大且個性敦厚穩重。",
    citesStatus: "常規進口",
    accentColor: "#eab308",
    badge: "敦厚紅緣鳳凰",
    featured: false,
    image: "images/5. (C. dickhardi).webp",
    tags: ["玻利維亞", "強健耐養", "溫和混養"]
  },
  {
    id: "cich-08",
    code: "DIPLOTAENIA",
    name: "秘魯二線短鯛 (雙帶短鯛)",
    enName: "Diplotaenia Dwarf Cichlid",
    sciName: "Apistogramma diplotaenia",
    category: "cichlids",
    categoryLabel: "南美精緻短鯛",
    difficulty: 4,
    tempMin: 24,
    tempMax: 29,
    phMin: 4.5,
    phMax: 5.8,
    ghMin: 1,
    ghMax: 3,
    sizeCm: 5.0,
    origin: "巴西內格羅河上游黑水流域",
    swimmingLayer: "中下層穿梭",
    temperament: "體型小巧 / 游動極為靈動",
    diet: "無節幼體、水蚤、微粒",
    substrate: "極酸性泥炭黑水底床",
    waterFlow: "極微弱水流",
    craftsmanTip: "體型纖細小巧，體側兩條黑線在尾柄處匯聚，在深色極軟黑水下散發出幽藍色金屬反光，是短鯛玩家的進階珍品。",
    citesStatus: "內格羅河限定輸入",
    accentColor: "#c084fc",
    badge: "黑水精靈雙線帶",
    featured: false,
    image: "images/50. (C. robineae super).jpg",
    tags: ["短鯛", "極軟黑水", "雙線帶", "內格羅河"]
  },

  // ==========================================
  // GROUP 6: 珍稀脂鯉與小型特異名品 (Tetras & Exotics)
  // ==========================================
  {
    id: "tetra-01",
    code: "CARDINAL",
    name: "頂級野生寶蓮燈 (日光燈之王)",
    enName: "Cardinal Tetra",
    sciName: "Paracheirodon axelrodi",
    category: "tetras",
    categoryLabel: "精品燈魚脂鯉",
    difficulty: 2,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.0,
    phMax: 6.8,
    ghMin: 1,
    ghMax: 5,
    sizeCm: 4.5,
    origin: "內格羅河與奧里諾科河流域 (Rio Negro / Orinoco)",
    swimmingLayer: "中層集群群游",
    temperament: "極度溫和 / 建議 20+ 隻群游",
    diet: "微細薄片、小型無節幼體、粉狀飼料",
    substrate: "水草底床、深色黑水底砂",
    waterFlow: "弱至中等緩流",
    craftsmanTip: "腹部鮮紅色彩一路貫穿至頭部下顎，在黑暗黑水環境中，體側藍綠色螢光線如雷射般刺眼。數十隻群游時極具視覺震撼力。",
    citesStatus: "常規野生大量檢疫輸入",
    accentColor: "#ef4444",
    badge: "南美燈魚之王",
    featured: false,
    image: "images/7. (Hoplisoma julii).webp",
    tags: ["寶蓮燈", "燈魚群游", "黑水生境", "螢光色帶"]
  },
  {
    id: "tetra-02",
    code: "ROYAL-TETRA",
    name: "皇室紅蓮燈 (克里燈 / 帝王燈)",
    enName: "Royal Tetra / Emperor Tetra",
    sciName: "Inpaichthys kerri",
    category: "tetras",
    categoryLabel: "精品燈魚脂鯉",
    difficulty: 2,
    tempMin: 23,
    tempMax: 27,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 4.0,
    origin: "巴西阿里普阿南河流域 (Rio Aripuana)",
    swimmingLayer: "中層水域",
    temperament: "活潑好動",
    diet: "微顆粒、水蚤、浮游生物",
    substrate: "水草林與沉木造景",
    waterFlow: "中等水流",
    craftsmanTip: "雄魚散發如皇家紫羅蘭般的深邃紫藍金屬光澤，脂鰭呈現亮麗粉紅色，在水草造景缸中如同飄逸的紫寶石。",
    citesStatus: "穩定人工繁殖",
    accentColor: "#818cf8",
    badge: "皇家紫羅蘭色澤",
    featured: false,
    image: "images/26.(C. nattereri blue).jpg",
    tags: ["帝王燈", "紫羅蘭", "水草造景", "精品脂鯉"]
  },
  {
    id: "tetra-03",
    code: "RUMMY-NOSE",
    name: "紅鼻剪刀 (水質活指標)",
    enName: "Rummy-nose Tetra",
    sciName: "Hemigrammus rhodostomus",
    category: "tetras",
    categoryLabel: "精品燈魚脂鯉",
    difficulty: 2,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 5.0,
    origin: "亞馬遜河下游與奧里諾科河流域",
    swimmingLayer: "中層緊湊群游",
    temperament: "集體群游性極強",
    diet: "微細薄片碎屑、冷凍水蚤",
    substrate: "細緻沙質底床",
    waterFlow: "中等水流",
    craftsmanTip: "頭部鮮紅如醉漢，尾鰭黑白斑馬紋如同剪刀開合。若水質惡化或溶氧不足，鼻部紅色會瞬間褪淡，是水族職人最信賴的水質活指標。",
    citesStatus: "市場穩定常備",
    accentColor: "#f43f5e",
    badge: "水質活指標紅鼻",
    featured: false,
    image: "images/27.  (C. bicolor).jpg",
    tags: ["紅鼻剪刀", "水質指標", "極致群游", "剪刀尾"]
  },
  {
    id: "tetra-04",
    code: "BLACK-GHOST",
    name: "黑魔鬼 (羽毛刀魚 / 綠翡翠刀)",
    enName: "Black Ghost Knifefish",
    sciName: "Apteronotus albifrons",
    category: "tetras",
    categoryLabel: "特異大師刀魚",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 4,
    ghMax: 12,
    sizeCm: 35.0,
    origin: "亞馬遜與奧里諾科河流域底層",
    swimmingLayer: "底層隱蔽物穿梭",
    temperament: "夜行性 / 微弱電場感應",
    diet: "沉底肉食錠、赤蟲、小魚小蝦",
    substrate: "沉木洞穴、岩石縫隙、透明壓克力管道",
    waterFlow: "中等水流",
    craftsmanTip: "通體漆黑如幽靈，透過微弱放電感應周遭障礙與獵物。腹鰭波浪狀擺動可實現前進、後退甚至上下無重力倒立游動，極具魔幻魅力。",
    citesStatus: "常規檢疫引進",
    accentColor: "#64748b",
    badge: "弱電導航魔幻幽靈",
    featured: false,
    image: "images/35.  (C. punctatus).jpg",
    tags: ["黑魔鬼", "弱電感應", "羽毛刀", "無重力游姿"]
  },
  {
    id: "tetra-05",
    code: "LYRETAIL-KILLI",
    name: "藍眼白金蝴蝶鱂 (琴尾鱂)",
    enName: "Cape Lopez Lyretail",
    sciName: "Aphyosemion australe",
    category: "tetras",
    categoryLabel: "多年生精品鱂魚",
    difficulty: 2,
    tempMin: 21,
    tempMax: 25,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 5.5,
    origin: "西非加彭與剛果沿海低地濕地",
    swimmingLayer: "中上層水域",
    temperament: "安靜優雅 / 喜跳躍 (務必加蓋)",
    diet: "冷凍微蟲、水蚤、微細薄片碎屑",
    substrate: "泥炭土、水草密植",
    waterFlow: "極微弱水流",
    craftsmanTip: "琴狀尾鰭上下延伸拉長，配上如同蝴蝶翅膀般的橙黃色與白色斑點。水面務必緊密加蓋，是多年生鱂魚中的經典藝術品。",
    citesStatus: "人工品系培育成熟",
    accentColor: "#f59e0b",
    badge: "西非琴尾蝴蝶鱂",
    featured: false,
    image: "images/37.  (C. reynoldsi).jpg",
    tags: ["鱂魚", "琴尾", "蝴蝶翅", "跳躍高手"]
  },
  {
    id: "tetra-06",
    code: "CONGO-TETRA",
    name: "剛果燈 (剛果帝王脂鯉)",
    enName: "Congo Tetra",
    sciName: "Phenacogrammus interruptus",
    category: "tetras",
    categoryLabel: "精品燈魚脂鯉",
    difficulty: 2,
    tempMin: 23,
    tempMax: 27,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 12,
    sizeCm: 8.5,
    origin: "非洲剛果河流域 (Congo River Basin)",
    swimmingLayer: "中層開闊水域",
    temperament: "大方溫和 / 搶食迅速",
    diet: "各類薄片、顆粒飼料、冷凍豐年蝦",
    substrate: "深色底砂與開闊游動空間",
    waterFlow: "中等水流",
    craftsmanTip: "大型脂鯉之王，魚鱗散發出彩虹般的光澤，雄魚尾鰭中央延長如同羽毛扇，在強光群游時極具視覺霸氣。",
    citesStatus: "人工繁殖成熟",
    accentColor: "#38bdf8",
    badge: "非洲彩虹羽扇脂鯉",
    featured: false,
    image: "images/39. (C. condiscipulus).jpg",
    tags: ["剛果燈", "彩虹光澤", "羽毛尾", "大體型脂鯉"]
  },
  {
    id: "tetra-07",
    code: "EMBER-TETRA",
    name: "噴火燈 (紅蓮微燈)",
    enName: "Ember Tetra",
    sciName: "Hyphessobrycon amandae",
    category: "tetras",
    categoryLabel: "精品燈魚脂鯉",
    difficulty: 1,
    tempMin: 23,
    tempMax: 28,
    phMin: 5.5,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 8,
    sizeCm: 2.0,
    origin: "巴西阿拉瓜亞河流域 (Rio Araguaia)",
    swimmingLayer: "中層水草茂密區",
    temperament: "極度溫馴 / 喜群居",
    diet: "微細粉末飼料、微小水蚤",
    substrate: "水草泥底床",
    waterFlow: "微弱水流",
    craftsmanTip: "體長僅 2 cm 的微型脂鯉，通體半透明橙紅色如同燃燒中的炭火火星。在一整片綠色水草造景中，呈現如同點點星火的視覺反差。",
    citesStatus: "市場常備穩定人工繁殖",
    accentColor: "#f97316",
    badge: "2cm 水草星火",
    featured: false,
    image: "images/43.(C. aeneus).webp",
    tags: ["噴火燈", "微型脂鯉", "草缸絕配", "火星橘"]
  },
  // ==========================================
  // GROUP 5: 經典野生與品系神仙魚大系 (Angelfish / Pterophyllum Master Series #51~#100)
  // ==========================================
  {
    id: "angel-01",
    code: "P-SILVER",
    name: "野生銀神仙 (原生型)",
    enName: "Silver Wild-Type Angelfish",
    sciName: "Pterophyllum scalare \"Wild Silver\"",
    category: "angelfish",
    categoryLabel: "原生野生型",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "亞馬遜河流域與秘魯水系 (Amazon Basin, Peru, Brazil)",
    swimmingLayer: "中層優雅游動",
    temperament: "溫和優雅 / 成魚護卵時具強烈領域性",
    diet: "豐年蝦、赤蟲、高品質薄片及顆粒",
    substrate: "天然河砂、南美沉木、巨大水蘭與皇冠草",
    waterFlow: "中等緩流",
    craftsmanTip: "銀白底色貫穿經典三至四道筆直黑斑帶，眼部虹膜呈現深紅色。是神仙魚一切人工改良品種的原始基石，野性強健、體態挺拔。",
    citesStatus: "常規穩定引進 / 人工與野生兼具",
    accentColor: "#94a3b8",
    badge: "經典野生原生型",
    featured: false,
    image: "images2/51.(Silver  Wild Type).png",
    tags: ["原生銀", "神仙魚基石", "經典黑斑帶", "紅眼虹膜"]
  },
  {
    id: "angel-02",
    code: "P-ALTUM",
    name: "埃及神仙 (奧里諾科高身神仙)",
    enName: "Altum Angelfish (Orinoco Angel)",
    sciName: "Pterophyllum altum",
    category: "angelfish",
    categoryLabel: "大師野生典藏",
    difficulty: 5,
    tempMin: 28,
    tempMax: 31,
    phMin: 4.5,
    phMax: 6.2,
    ghMin: 1,
    ghMax: 4,
    sizeCm: 30.0,
    origin: "哥倫比亞與委內瑞拉奧里諾科河流域 (Rio Orinoco Basin)",
    swimmingLayer: "中上層縱深水域",
    temperament: "高貴敏感 / 需超高水深 (> 60cm)",
    diet: "活餌無節幼蟲、冷凍紅蟲、特級緩沉顆粒",
    substrate: "極軟黑水、沉木落葉造景、極細天然矽砂",
    waterFlow: "溫和緩流 / 超高潔淨水質",
    craftsmanTip: "神仙魚界無可爭議的帝王，具備標誌性的凹鼻鞍部與極度垂直高聳的上下鰭，成魚展鰭可達 30 cm 以上。極度要求超低 TDS (< 50 ppm) 與極致穩定的弱酸軟水。",
    citesStatus: "野生季節限定 / 大師級頂級珍品",
    accentColor: "#d97706",
    badge: "神仙魚帝王 30cm展鰭",
    featured: true,
    image: "images2/52.(Altum Angelfish).png",
    tags: ["埃及神仙", "大師挑戰", "奧里諾科河", "極度高身", "帝王級"]
  },
  {
    id: "angel-03",
    code: "P-LEOPOLDI",
    name: "藍天使神仙 (利氏神仙 / 長吻神仙)",
    enName: "Leopold's Angelfish (Tear-drop Angel)",
    sciName: "Pterophyllum leopoldi",
    category: "angelfish",
    categoryLabel: "野生珍稀型",
    difficulty: 4,
    tempMin: 26,
    tempMax: 30,
    phMin: 5.5,
    phMax: 6.8,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 10.0,
    origin: "巴西亞馬遜河幹流與普魯斯河下游 (Rio Purus)",
    swimmingLayer: "中層水草沉木區",
    temperament: "體型小巧精悍 / 略帶領域防禦性",
    diet: "水蚤、豐年蝦、小型微肉食顆粒",
    substrate: "細緻黑泥沙配沉木樹皮",
    waterFlow: "中等水流",
    craftsmanTip: "三種野生原生神仙中體型最精巧者，背部近尾柄處有一顆標誌性濃黑圓斑（淚滴斑），成魚鰓蓋與腹側閃爍金屬天青藍冷光。",
    citesStatus: "野生限量檢疫進口",
    accentColor: "#0284c7",
    badge: "淚滴藍光精靈",
    featured: false,
    image: "images2/53.( Leopold's Angelfish ).png",
    tags: ["利氏神仙", "藍天使", "淚滴斑", "原生迷你神仙"]
  },
  {
    id: "angel-04",
    code: "ANGEL-BLACK-01",
    name: "黑幻影神仙 (深黑神仙)",
    enName: "Black / Dark Angelfish",
    sciName: "Pterophyllum scalare var. \"Black Dark\"",
    category: "angelfish",
    categoryLabel: "經典黑化品系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "人工改良品系 (黑化基因 D/+)",
    swimmingLayer: "中層游動",
    temperament: "溫和優雅 / 愛群游",
    diet: "各類高級螺旋藻薄片、沉水赤蟲、顆粒",
    substrate: "淺色河砂 (高對比凸顯體色)",
    waterFlow: "中等緩流",
    craftsmanTip: "攜帶單個深黑基因 (Dark Gene)，體色呈現濃郁的玄鐵黑或炭灰色，在強光下隱約可見底層斑馬暗紋，游動時如黑天鵝絨般神秘莊嚴。",
    citesStatus: "人工繁育穩定",
    accentColor: "#334155",
    badge: "玄鐵深黑",
    featured: false,
    image: "images2/54.(Black  Dark).png",
    tags: ["黑神仙", "單黑基因", "黑天鵝絨", "經典品系"]
  },
  {
    id: "angel-05",
    code: "ANGEL-DBL-DARK",
    name: "雙重極黑神仙 (純墨黑神仙)",
    enName: "Double Dark Black Angelfish",
    sciName: "Pterophyllum scalare var. \"Double Dark (D/D)\"",
    category: "angelfish",
    categoryLabel: "極致黑化品系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 14.0,
    origin: "純系同型純合黑化繁育 (D/D 雙黑基因)",
    swimmingLayer: "中層優雅懸浮",
    temperament: "沉穩靜態 / 幼魚需細緻呵護",
    diet: "高蛋白豐年蝦、冷凍赤蟲、免疫強化薄片",
    substrate: "亮白細砂造景 (極致對比)",
    waterFlow: "緩慢溫和水流",
    craftsmanTip: "純合子雙黑基因使得全身連眼部、鰭膜皆達到 100% 不透光的極致深邃黑。幼魚生長速度較慢，需維持水質高度純淨與豐沛餌料。",
    citesStatus: "專業繁育大師品系",
    accentColor: "#0f172a",
    badge: "100% 絕對純黑",
    featured: false,
    image: "images2/55.( Double Dark Black ).png",
    tags: ["極黑神仙", "雙黑基因", "純黑不透光", "大師培育"]
  },
  {
    id: "angel-06",
    code: "ANGEL-LACE-01",
    name: "黑蕾絲神仙 (黑薄紗神仙)",
    enName: "Black Lace Angelfish",
    sciName: "Pterophyllum scalare var. \"Black Lace (D/+)\"",
    category: "angelfish",
    categoryLabel: "蕾絲斑紋品系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "人工改良經典蕾絲斑系",
    swimmingLayer: "中層水域",
    temperament: "溫順沉著 / 與小型燈魚絕配",
    diet: "螺旋藻薄片、微細顆粒、冷凍赤蟲",
    substrate: "細砂與水草底床",
    waterFlow: "中等水流",
    craftsmanTip: "黑化基因與野生條紋的完美平衡點。魚鰭邊緣與條紋呈現細緻如古典蕾絲般的半透光幾何網紋，在側光下散發極致復古高雅氣質。",
    citesStatus: "市場長青名種",
    accentColor: "#475569",
    badge: "古典蕾絲網紋",
    featured: false,
    image: "images2/56.(Black Lace).png",
    tags: ["黑蕾絲", "薄紗暗紋", "優雅古典", "經典品系"]
  },
  {
    id: "angel-07",
    code: "ANGEL-MARBLE-01",
    name: "大理石神仙 (黑白潑墨神仙)",
    enName: "Marble Angelfish",
    sciName: "Pterophyllum scalare var. \"Marble (M/+)\"",
    category: "angelfish",
    categoryLabel: "大理石潑墨系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.5,
    ghMin: 3,
    ghMax: 9,
    sizeCm: 16.0,
    origin: "人工品系 (大理石基因 M)",
    swimmingLayer: "中層水域",
    temperament: "活躍好奇 / 搶食迅速",
    diet: "沉浮薄片、乾操赤蟲、豐年蝦",
    substrate: "各類天然底床皆宜",
    waterFlow: "中等水流",
    craftsmanTip: "體表覆蓋黑白相間如水墨畫或天然大理石般的隨機潑墨斑塊。每隻個體的斑塊走向皆獨一無二，如水下流動的水墨藝術品。",
    citesStatus: "常規熱門品種",
    accentColor: "#6b7280",
    badge: "獨一無二水墨潑紋",
    featured: false,
    image: "images2/57.(Marble).png",
    tags: ["大理石", "潑墨花紋", "每隻皆獨特", "強健好養"]
  },
  {
    id: "angel-08",
    code: "ANGEL-GOLD-01",
    name: "黃金神仙 (金神仙 / 蜜桃黃金)",
    enName: "Gold Angelfish",
    sciName: "Pterophyllum scalare var. \"Gold (g/g)\"",
    category: "angelfish",
    categoryLabel: "黃金金屬系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 29,
    phMin: 6.2,
    phMax: 7.4,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "隱性黃金基因 (g/g) 選育",
    swimmingLayer: "中層水域",
    temperament: "溫馴安詳 / 適合混養",
    diet: "含蝦紅素與胡蘿蔔素之增色薄片、冷凍活餌",
    substrate: "深色水草泥 (襯托金黃光澤)",
    waterFlow: "中等水流",
    craftsmanTip: "全身條紋完全退去，取而代之的是閃耀的金黃至香檳蜜桃色澤，成熟個體背部與額頭常透出深橙金色的金冠光暈。",
    citesStatus: "市場經典熱門品系",
    accentColor: "#eab308",
    badge: "純金蜜桃光芒",
    featured: false,
    image: "images2/58.(Gold).png",
    tags: ["黃金神仙", "金冠頭", "無紋純色", "富貴典雅"]
  },
  {
    id: "angel-09",
    code: "ANGEL-GM-01",
    name: "金大理石神仙 (金頂水墨神仙)",
    enName: "Gold Marble Angelfish",
    sciName: "Pterophyllum scalare var. \"Gold Marble (Gm/Gm)\"",
    category: "angelfish",
    categoryLabel: "大理石潑墨系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.5,
    origin: "金大理石基因選育品系",
    swimmingLayer: "中層水域",
    temperament: "活潑好動 / 喜群游",
    diet: "豐年蝦、赤蟲、高品質綜合顆粒",
    substrate: "天然河砂、水草造景",
    waterFlow: "中等緩流",
    craftsmanTip: "結合黃金與大理石基因，頭部冠頂呈現金燦橘黃，軀幹交錯著深黑大理石水墨斑紋，對比鮮明強烈。",
    citesStatus: "人工繁育普及穩定",
    accentColor: "#ca8a04",
    badge: "金頂潑墨雙絕",
    featured: false,
    image: "images2/59.(Gold Marble).png",
    tags: ["金大理石", "金頂黑斑", "高對比", "華麗花紋"]
  },
  {
    id: "angel-10",
    code: "ANGEL-ZEBRA-01",
    name: "斑馬神仙 (多紋神仙)",
    enName: "Zebra Angelfish",
    sciName: "Pterophyllum scalare var. \"Zebra (Z/+)\"",
    category: "angelfish",
    categoryLabel: "多條紋斑馬系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 16.0,
    origin: "斑馬顯性基因 (Z) 品系",
    swimmingLayer: "中層水域",
    temperament: "沉穩優美 / 展鰭極挺拔",
    diet: "各類薄片、顆粒、冷凍赤蟲",
    substrate: "天然河砂",
    waterFlow: "中等水流",
    craftsmanTip: "不同於野生型的3-4道黑條紋，斑馬神仙體側具備 4~6 道整齊排列的縱向墨黑斑馬紋，展鰭時如琴弦般律動。",
    citesStatus: "常規穩定進口",
    accentColor: "#64748b",
    badge: "六道琴弦黑紋",
    featured: false,
    image: "images2/60.(Zebra).png",
    tags: ["斑馬神仙", "多條紋", "工整對稱", "經典品系"]
  },
  {
    id: "angel-11",
    code: "ANGEL-ZEBRA-LACE",
    name: "斑馬蕾絲神仙 (薄紗斑馬)",
    enName: "Zebra Lace Angelfish",
    sciName: "Pterophyllum scalare var. \"Zebra Lace (Z/+, D/+)\"",
    category: "angelfish",
    categoryLabel: "蕾絲斑紋品系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 16.0,
    origin: "斑馬基因 (Z) 複合黑化基因 (D)",
    swimmingLayer: "中層水域",
    temperament: "溫和優雅",
    diet: "優質浮性與緩沉飼料、冷凍豐年蝦",
    substrate: "細緻天然砂",
    waterFlow: "中等水流",
    craftsmanTip: "斑馬多道條紋與黑蕾絲半透光鰭膜的極致融合，尾鰭與背鰭邊緣如同黑色蕾絲網紋，層次豐富幽邃。",
    citesStatus: "玩家級精緻品系",
    accentColor: "#475569",
    badge: "斑馬薄紗雙重奏",
    featured: false,
    image: "images2/61.( Zebra Lace ).png",
    tags: ["斑馬蕾絲", "雙基因複合", "網紋鰭膜", "細緻紋理"]
  },
  {
    id: "angel-12",
    code: "ANGEL-SMOKEY-01",
    name: "煙燻神仙 (灰煙神仙)",
    enName: "Smokey Angelfish",
    sciName: "Pterophyllum scalare var. \"Smokey (Sm/+)\"",
    category: "angelfish",
    categoryLabel: "煙燻漸層系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "煙燻顯性基因 (Sm/+)",
    swimmingLayer: "中層游動",
    temperament: "溫順靜謐",
    diet: "高品質薄片、赤蟲、顆粒飼料",
    substrate: "白砂底床與綠植水草缸",
    waterFlow: "中等緩流",
    craftsmanTip: "軀幹後半部籠罩著如晨霧或木炭青煙般的漸層灰黑色澤，邊緣不規則暈染，帶來迷幻的莫蘭迪色系水下美學。",
    citesStatus: "穩定人工培育",
    accentColor: "#64748b",
    badge: "水下水墨煙霧",
    featured: false,
    image: "images2/62.( Smokey ).png",
    tags: ["煙燻神仙", "青煙漸層", "莫蘭迪灰", "迷幻暈染"]
  },
  {
    id: "angel-13",
    code: "ANGEL-CHOC-01",
    name: "巧克力神仙 (雙重煙燻神仙)",
    enName: "Chocolate Angelfish",
    sciName: "Pterophyllum scalare var. \"Chocolate (Sm/Sm)\"",
    category: "angelfish",
    categoryLabel: "煙燻漸層系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.0,
    origin: "純合子雙煙燻基因 (Sm/Sm)",
    swimmingLayer: "中層游動",
    temperament: "優雅從容",
    diet: "豐年蝦、赤蟲、特級微粒",
    substrate: "淺色純淨底砂",
    waterFlow: "緩慢水流",
    craftsmanTip: "同型純合雙煙燻基因使體色加深為深濃的可可黑巧克力色，幾乎覆蓋全身三分之二以上，散發深邃絲滑的古銅光澤。",
    citesStatus: "玩家級進階品系",
    accentColor: "#451a03",
    badge: "絲滑深濃可可",
    featured: false,
    image: "images2/63.( Chocolate ).png",
    tags: ["巧克力神仙", "雙煙燻純合", "可可色澤", "絲滑深邃"]
  },
  {
    id: "angel-14",
    code: "ANGEL-HALF-01",
    name: "半黑神仙 (黑後半神仙)",
    enName: "Halfblack Angelfish",
    sciName: "Pterophyllum scalare var. \"Halfblack (h/h)\"",
    category: "angelfish",
    categoryLabel: "幾何色塊系",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 14.5,
    origin: "隱性半黑基因 (h/h)",
    swimmingLayer: "中層水域",
    temperament: "溫和膽小 / 需穩定水質",
    diet: "高蛋白薄片、無節幼體、冷凍赤蟲",
    substrate: "天然細緻河砂",
    waterFlow: "中等緩流",
    craftsmanTip: "自背鰭中央至尾部呈現刀切般分明的全黑半身，前半身則保持閃亮純銀，黑白界線分明，是水族遺傳學上的經典幾何之作。",
    citesStatus: "老牌經典珍品",
    accentColor: "#1e293b",
    badge: "幾何黑白對切",
    featured: false,
    image: "images2/64.( Halfblack ).png",
    tags: ["半黑神仙", "黑後半", "刀切界線", "幾何美感"]
  },
  {
    id: "angel-15",
    code: "ANGEL-ALB-01",
    name: "白化神仙 (紅眼白子神仙)",
    enName: "Albino Angelfish",
    sciName: "Pterophyllum scalare var. \"Albino (a/a)\"",
    category: "angelfish",
    categoryLabel: "白化紅眼系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.4,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 14.0,
    origin: "隱性白化基因 (a/a)",
    swimmingLayer: "中層水域",
    temperament: "視力稍弱 / 溫和不具攻擊性",
    diet: "易辨識之浮性薄片、冷凍赤蟲、豐年蝦",
    substrate: "深色軟質底床 (防強光反射刺眼)",
    waterFlow: "緩流水流 / 柔和漫射光源",
    craftsmanTip: "全身黑色素完全缺失，體色呈現晶瑩乳白透粉，眼球如紅寶石般透亮。避免強烈直射強光，以弱光水草造景能展現極致純淨之美。",
    citesStatus: "人工繁育穩定",
    accentColor: "#f43f5e",
    badge: "紅寶石白子精靈",
    featured: false,
    image: "images2/65.( Albino ).png",
    tags: ["白化神仙", "紅眼白子", "純白無瑕", "柔光愛好"]
  },
  {
    id: "angel-16",
    code: "ANGEL-GHOST-01",
    name: "幽靈神仙 (無條紋透亮神仙)",
    enName: "Ghost Angelfish",
    sciName: "Pterophyllum scalare var. \"Ghost (S/+)\"",
    category: "angelfish",
    categoryLabel: "透明無斑系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "單條紋消除基因 (S/+)",
    swimmingLayer: "中層水域",
    temperament: "溫順合群",
    diet: "各類綜合薄片、赤蟲",
    substrate: "細緻水草底砂",
    waterFlow: "中等水流",
    craftsmanTip: "野生條紋幾乎完全消失，僅在眼部或尾柄殘留極微弱暗點。通體銀亮半透明，游動時如幽靈般在光影中忽隱忽現。",
    citesStatus: "基礎繁育品系",
    accentColor: "#cbd5e1",
    badge: "半透光影幽靈",
    featured: false,
    image: "images2/66.( Ghost ).png",
    tags: ["幽靈神仙", "無紋透亮", "光影穿透", "溫順品種"]
  },
  {
    id: "angel-17",
    code: "ANGEL-BGHOST",
    name: "黑幽靈神仙 (幻影黑幽靈)",
    enName: "Black Ghost Angelfish",
    sciName: "Pterophyllum scalare var. \"Black Ghost (D/+, S/+)\"",
    category: "angelfish",
    categoryLabel: "黑化幽靈系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "黑化基因 (D/+) 複合無紋基因 (S/+)",
    swimmingLayer: "中層水域",
    temperament: "優雅靜態",
    diet: "沉底浮性多元飼料、豐年蝦",
    substrate: "淺色天然河砂",
    waterFlow: "中等水流",
    craftsmanTip: "消除所有條紋的深黑神仙，呈現整片平滑均勻的墨色絲絨，無任何雜紋干擾，極具沉穩內斂的極簡主義美學。",
    citesStatus: "人工繁育穩定",
    accentColor: "#334155",
    badge: "極簡墨黑絲絨",
    featured: false,
    image: "images2/67.( Black Ghost ).png",
    tags: ["黑幽靈", "均勻墨色", "無條紋黑", "極簡美學"]
  },
  {
    id: "angel-18",
    code: "ANGEL-BLUSH-01",
    name: "胭脂紅腮神仙 (害羞神仙)",
    enName: "Blushing Angelfish",
    sciName: "Pterophyllum scalare var. \"Blushing (S/S)\"",
    category: "angelfish",
    categoryLabel: "胭脂紅腮系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "雙條紋消除基因 (S/S)",
    swimmingLayer: "中層游動",
    temperament: "害羞溫和",
    diet: "豐年蝦幼蟲、高適口性薄片",
    substrate: "天然水草砂",
    waterFlow: "中等緩流",
    craftsmanTip: "純合子無紋基因使得鰓蓋完全透明，內部鮮紅色的鰓絲清晰可見，宛如少女臉頰泛起的天然胭脂紅暈。",
    citesStatus: "經典人氣品種",
    accentColor: "#fb7185",
    badge: "天然胭脂紅暈",
    featured: false,
    image: "images2/68.( Blushing ).png",
    tags: ["紅腮神仙", "胭脂紅", "透明鰓蓋", "少女紅暈"]
  },
  {
    id: "angel-19",
    code: "ANGEL-SUNSET-01",
    name: "夕陽神仙 (落日橘金神仙)",
    enName: "Sunset Angelfish",
    sciName: "Pterophyllum scalare var. \"Sunset (g/g, S/+)\"",
    category: "angelfish",
    categoryLabel: "夕陽霞光系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 29,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "黃金基因 (g/g) 複合單無紋基因 (S/+)",
    swimmingLayer: "中層水域",
    temperament: "活潑好動 / 喜群聚",
    diet: "增色薄片、冷凍活餌、微粒",
    substrate: "沉木黑水草缸",
    waterFlow: "中等水流",
    craftsmanTip: "頭頂與背脊染上一層如晚霞般的濃郁橙橘色，向腹部漸變為銀白，宛如亞馬遜日落時分映照在水面的金色餘暉。",
    citesStatus: "廣受歡迎暖色系",
    accentColor: "#f97316",
    badge: "晚霞落日金橙",
    featured: false,
    image: "images2/69.( Sunset ).png",
    tags: ["夕陽神仙", "晚霞橘冠", "金橙漸層", "溫暖色系"]
  },
  {
    id: "angel-20",
    code: "ANGEL-SUN-BLUSH",
    name: "夕陽紅腮神仙 (霞光胭脂神仙)",
    enName: "Sunset Blushing Angelfish",
    sciName: "Pterophyllum scalare var. \"Sunset Blushing (g/g, S/S)\"",
    category: "angelfish",
    categoryLabel: "夕陽霞光系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 29,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "黃金基因 (g/g) 複合雙無紋基因 (S/S)",
    swimmingLayer: "中層水域",
    temperament: "溫順迷人",
    diet: "高品質增紅薄片、豐年蝦",
    substrate: "細砂與水草缸",
    waterFlow: "中等緩流",
    craftsmanTip: "雙無紋純合基因帶來透明紅鰓，頭頂更覆蓋耀眼的金橙冠頂，是繁育錦鯉神仙（三色神仙）不可或缺的頂級母本。",
    citesStatus: "精品繁育名種",
    accentColor: "#ea580c",
    badge: "金橙紅腮雙絕",
    featured: false,
    image: "images2/70.( Sunset Blushing ).png",
    tags: ["夕陽紅腮", "雙無紋黃金", "紅腮金頂", "錦鯉神仙母本"]
  },
  {
    id: "angel-21",
    code: "ANGEL-KOI-01",
    name: "錦鯉神仙 (三色神仙 / 紅白黑神仙)",
    enName: "Koi Angelfish",
    sciName: "Pterophyllum scalare var. \"Koi (Gm/Gm, S/S)\"",
    category: "angelfish",
    categoryLabel: "錦鯉三色系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 16.0,
    origin: "金大理石基因複合雙無紋基因 (Gm/Gm, S/S)",
    swimmingLayer: "中層水域",
    temperament: "活潑亮眼 / 魚缸視覺焦點",
    diet: "螺旋藻薄片、優質增紅顆粒、冷凍赤蟲",
    substrate: "深色底砂與沉木綠植",
    waterFlow: "中等水流",
    craftsmanTip: "水族界的經典三色王者！白玉底色上分佈著墨黑潑斑，頭頂散發如同日本錦鯉丹頂般的鮮紅或濃橘色塊，極富東方美學神韻。",
    citesStatus: "全球超人氣旗艦改良品系",
    accentColor: "#dc2626",
    badge: "東方水墨錦鯉",
    featured: true,
    image: "images2/71.( Koi ).png",
    tags: ["錦鯉神仙", "三色神仙", "丹頂橘冠", "超高人氣"]
  },
  {
    id: "angel-22",
    code: "ANGEL-CLOWN-01",
    name: "小丑神仙 (碎點斑馬神仙)",
    enName: "Clown Angelfish",
    sciName: "Pterophyllum scalare var. \"Clown (Z/+, S/+)\"",
    category: "angelfish",
    categoryLabel: "斑點碎紋系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.5,
    origin: "斑馬基因複合無紋基因",
    swimmingLayer: "中層游動",
    temperament: "活躍靈動",
    diet: "各類多元微粒飼料、活體無節幼體",
    substrate: "天然河砂",
    waterFlow: "中等水流",
    craftsmanTip: "條紋斷裂碎化成如同小丑戲服般跳躍的點狀斑紋與短橫紋，體態俏皮靈動，極具趣味性與辨識度。",
    citesStatus: "穩定人工繁育",
    accentColor: "#64748b",
    badge: "俏皮小丑碎斑",
    featured: false,
    image: "images2/72.( Clown ).png",
    tags: ["小丑神仙", "斷裂斑紋", "跳躍點斑", "俏皮靈動"]
  },
  {
    id: "angel-23",
    code: "ANGEL-LEOPARD-01",
    name: "花豹神仙 (豹紋斑點神仙)",
    enName: "Leopard Angelfish",
    sciName: "Pterophyllum scalare var. \"Leopard (Sm/Sm, Z/Z)\"",
    category: "angelfish",
    categoryLabel: "斑點碎紋系",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 16.0,
    origin: "煙燻與斑馬純合基因選育",
    swimmingLayer: "中層水域",
    temperament: "威風自信",
    diet: "高蛋白赤蟲、豐年蝦、特級顆粒",
    substrate: "天然細緻沙床",
    waterFlow: "中等水流",
    craftsmanTip: "全身均勻密佈如同花豹皮毛般的深黑圓形斑點，幼魚期條紋隨成長逐漸破碎為密集錢幣豹斑，極富野性掠食氣質。",
    citesStatus: "玩家級精緻品系",
    accentColor: "#78350f",
    badge: "叢林花豹斑點",
    featured: false,
    image: "images2/73.( Leopard ).png",
    tags: ["花豹神仙", "豹紋斑點", "野性美感", "密集碎斑"]
  },
  {
    id: "angel-24",
    code: "ANGEL-SMK-LEOP",
    name: "煙燻花豹神仙 (灰煙豹斑神仙)",
    enName: "Smokey Leopard Angelfish",
    sciName: "Pterophyllum scalare var. \"Smokey Leopard\"",
    category: "angelfish",
    categoryLabel: "煙燻複合系",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 16.0,
    origin: "煙燻基因複合花豹基因",
    swimmingLayer: "中層水域",
    temperament: "從容典雅",
    diet: "豐年蝦、薄片飼料、微粒餌料",
    substrate: "細白砂與沉木水草缸",
    waterFlow: "中等緩流",
    craftsmanTip: "後半身的灰煙漸層底色上疊加了深色豹斑，如穿梭在晨霧中的雪豹，層次感與立體感極度強烈。",
    citesStatus: "精品培育品系",
    accentColor: "#57534e",
    badge: "迷霧雪豹紋理",
    featured: false,
    image: "images2/74.( Smokey Leopard ).png",
    tags: ["煙燻花豹", "灰煙豹紋", "雙重質感", "層次豐富"]
  },
  {
    id: "angel-25",
    code: "ANGEL-CHOC-LEOP",
    name: "巧克力花豹神仙 (可可豹紋神仙)",
    enName: "Chocolate Leopard Angelfish",
    sciName: "Pterophyllum scalare var. \"Chocolate Leopard\"",
    category: "angelfish",
    categoryLabel: "煙燻複合系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 16.0,
    origin: "雙煙燻巧克力基因複合花豹斑系",
    swimmingLayer: "中層游動",
    temperament: "沉穩霸氣",
    diet: "高蛋白赤蟲、豐年蝦幼蟲",
    substrate: "淺色天然矽砂",
    waterFlow: "中等緩流",
    craftsmanTip: "深濃的可可色底色與密集的漆黑豹點完美交融，在金色側光照射下展現如古銅雕塑般的深沉光澤。",
    citesStatus: "玩家級進階收藏",
    accentColor: "#3b1d07",
    badge: "深濃可可豹影",
    featured: false,
    image: "images2/75.( Chocolate Leopard ).png",
    tags: ["巧克力花豹", "深黑豹斑", "古銅光澤", "尊貴典雅"]
  },
  {
    id: "angel-26",
    code: "ANGEL-SMK-LACE",
    name: "煙燻蕾絲神仙 (薄紗灰煙神仙)",
    enName: "Smokey Lace Angelfish",
    sciName: "Pterophyllum scalare var. \"Smokey Lace (Sm/+, D/+)\"",
    category: "angelfish",
    categoryLabel: "蕾絲斑紋品系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.5,
    origin: "煙燻基因複合黑蕾絲基因",
    swimmingLayer: "中層水域",
    temperament: "安靜溫和",
    diet: "優質螺旋藻薄片、微細顆粒",
    substrate: "天然細緻砂",
    waterFlow: "中等水流",
    craftsmanTip: "煙燻的柔和霧感與黑蕾絲的精緻網狀鰭條結合，尾鰭如同一襲被煙霧籠罩的黑色蕾絲禮服。",
    citesStatus: "穩定繁育品系",
    accentColor: "#52525b",
    badge: "煙霧蕾絲晚禮服",
    featured: false,
    image: "images2/76.( Smokey Lace ).png",
    tags: ["煙燻蕾絲", "薄紗漸層", "細膩鰭膜", "優雅古典"]
  },
  {
    id: "angel-27",
    code: "ANGEL-CHOC-LACE",
    name: "巧克力蕾絲神仙 (可可蕾絲神仙)",
    enName: "Chocolate Lace Angelfish",
    sciName: "Pterophyllum scalare var. \"Chocolate Lace (Sm/Sm, D/+)\"",
    category: "angelfish",
    categoryLabel: "蕾絲斑紋品系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.5,
    origin: "雙煙燻基因複合黑蕾絲基因",
    swimmingLayer: "中層水域",
    temperament: "沉著典雅",
    diet: "豐年蝦、赤蟲、高品質微粒",
    substrate: "淺色天然砂",
    waterFlow: "中等緩流",
    craftsmanTip: "厚實深黑的可可色調覆蓋軀幹，背鰭與尾鰭展開時露出精雕細琢的深棕色蕾絲網紋，尊貴高雅。",
    citesStatus: "精品玩家珍藏",
    accentColor: "#422006",
    badge: "深濃可可蕾絲",
    featured: false,
    image: "images2/77.( Chocolate Lace ).png",
    tags: ["巧克力蕾絲", "深棕網紋", "絲滑高雅", "精緻鰭膜"]
  },
  {
    id: "angel-28",
    code: "ANGEL-SMK-MARB",
    name: "煙燻大理石神仙 (灰煙水墨神仙)",
    enName: "Smokey Marble Angelfish",
    sciName: "Pterophyllum scalare var. \"Smokey Marble (Sm/+, M/+)\"",
    category: "angelfish",
    categoryLabel: "大理石潑墨系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 16.0,
    origin: "煙燻基因複合大理石基因",
    swimmingLayer: "中層水域",
    temperament: "活躍好群游",
    diet: "各類綜合薄片、赤蟲、豐年蝦",
    substrate: "各類底床皆宜",
    waterFlow: "中等水流",
    craftsmanTip: "大理石黑白潑墨的俐落斑塊與煙燻的青灰漸層暈染相結合，營造出如同傳統水墨山水畫般煙雨朦朧的意境。",
    citesStatus: "穩定人工品系",
    accentColor: "#4b5563",
    badge: "煙雨朦朧潑墨",
    featured: false,
    image: "images2/78.( Smokey Marble ).png",
    tags: ["煙燻大理石", "水墨山水", "暈染潑墨", "藝術感"]
  },
  {
    id: "angel-29",
    code: "ANGEL-CHOC-MARB",
    name: "巧克力大理石神仙 (深濃可可潑墨神仙)",
    enName: "Chocolate Marble Angelfish",
    sciName: "Pterophyllum scalare var. \"Chocolate Marble (Sm/Sm, M/+)\"",
    category: "angelfish",
    categoryLabel: "大理石潑墨系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 16.0,
    origin: "雙煙燻基因複合大理石基因",
    swimmingLayer: "中層水域",
    temperament: "從容自信",
    diet: "高蛋白赤蟲、豐年蝦、顆粒飼料",
    substrate: "天然白矽砂",
    waterFlow: "中等緩流",
    craftsmanTip: "深濃可可色與深黑大理石斑塊重疊交錯，斑塊密度極高，呈現如黑森林蛋糕般的濃密醇厚質感。",
    citesStatus: "精品繁育名種",
    accentColor: "#3f1d0b",
    badge: "黑森林醇厚可可",
    featured: false,
    image: "images2/79.( Chocolate Marble ).png",
    tags: ["巧克力大理石", "濃郁可可", "高密度潑斑", "沉穩霸氣"]
  },
  {
    id: "angel-30",
    code: "ANGEL-SMK-GM",
    name: "煙燻金大理石神仙 (金冠煙燻潑墨)",
    enName: "Smokey Gold Marble Angelfish",
    sciName: "Pterophyllum scalare var. \"Smokey Gold Marble\"",
    category: "angelfish",
    categoryLabel: "大理石潑墨系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 16.0,
    origin: "煙燻、金大理石多基因複合選育",
    swimmingLayer: "中層水域",
    temperament: "活潑好動",
    diet: "綜合薄片、赤蟲、豐年蝦",
    substrate: "天然河砂、沉木水草",
    waterFlow: "中等水流",
    craftsmanTip: "頭部金黃璀璨，體側兼具大理石潑墨與青灰煙燻雙重層次，色彩飽和豐富，水草缸中極為耀眼。",
    citesStatus: "穩定人工繁育",
    accentColor: "#b45309",
    badge: "金冠三重色彩",
    featured: false,
    image: "images2/80.( Smokey Gold Marble ).png",
    tags: ["煙燻金大理石", "金頂煙燻", "三色交織", "色彩斑斕"]
  },
  {
    id: "angel-31",
    code: "ANGEL-CHOC-GM",
    name: "巧克力金大理石神仙 (金頂可可潑墨)",
    enName: "Chocolate Gold Marble Angelfish",
    sciName: "Pterophyllum scalare var. \"Chocolate Gold Marble\"",
    category: "angelfish",
    categoryLabel: "大理石潑墨系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 16.0,
    origin: "雙煙燻基因複合金大理石基因",
    swimmingLayer: "中層水域",
    temperament: "沉穩端莊",
    diet: "高蛋白赤蟲、豐年蝦幼蟲",
    substrate: "天然細緻底床",
    waterFlow: "中等緩流",
    craftsmanTip: "金黃色的額頭與背部冠頂，搭配深濃醇厚的可可大理石潑墨軀幹，宛如金箔鑲嵌在黑巧克力的奢華藝術品。",
    citesStatus: "精品大師品系",
    accentColor: "#92400e",
    badge: "金箔可可極致",
    featured: false,
    image: "images2/81.( Chocolate Gold Marble ).png",
    tags: ["巧克力金大理石", "金箔鑲嵌", "奢華質感", "大師改良"]
  },
  {
    id: "angel-32",
    code: "ANGEL-SMK-HALF",
    name: "煙燻半黑神仙 (灰煙半黑神仙)",
    enName: "Smokey Halfblack Angelfish",
    sciName: "Pterophyllum scalare var. \"Smokey Halfblack (Sm/+, h/h)\"",
    category: "angelfish",
    categoryLabel: "幾何色塊系",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "煙燻基因複合半黑基因",
    swimmingLayer: "中層水域",
    temperament: "溫和敏感",
    diet: "豐年蝦、赤蟲、薄片飼料",
    substrate: "天然細緻河砂",
    waterFlow: "中等緩流",
    craftsmanTip: "半黑的幾何色塊邊界被煙燻基因柔化為優美的漸層黑幕，前半身清亮如銀，後半身如夜幕降臨。",
    citesStatus: "精緻選育名品",
    accentColor: "#334155",
    badge: "夜幕降臨漸變",
    featured: false,
    image: "images2/82.( Smokey Halfblack ).png",
    tags: ["煙燻半黑", "柔化色塊", "幾何漸層", "夜幕黑"]
  },
  {
    id: "angel-33",
    code: "ANGEL-CHOC-HALF",
    name: "巧克力半黑神仙 (可可半黑神仙)",
    enName: "Chocolate Halfblack Angelfish",
    sciName: "Pterophyllum scalare var. \"Chocolate Halfblack (Sm/Sm, h/h)\"",
    category: "angelfish",
    categoryLabel: "幾何色塊系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.0,
    origin: "雙煙燻基因複合半黑基因",
    swimmingLayer: "中層水域",
    temperament: "典雅沉著",
    diet: "高蛋白赤蟲、優質無節幼體",
    substrate: "淺色天然矽砂",
    waterFlow: "中等緩流",
    craftsmanTip: "後半身呈現厚實濃烈的黑巧克力色澤，前半身則呈現暖銀色光芒，色塊分明且帶有溫潤的咖啡色光澤。",
    citesStatus: "珍稀改良品系",
    accentColor: "#291305",
    badge: "醇黑可可半身",
    featured: false,
    image: "images2/83.( Chocolate Halfblack ).png",
    tags: ["巧克力半黑", "濃郁可可", "幾何半身", "溫潤色調"]
  },
  {
    id: "angel-34",
    code: "ANGEL-SMK-PEARL",
    name: "煙燻珍珠鱗神仙 (灰煙鑽石鱗神仙)",
    enName: "Smokey Pearlscale Angelfish",
    sciName: "Pterophyllum scalare var. \"Smokey Pearlscale (Sm/+, p/p)\"",
    category: "angelfish",
    categoryLabel: "特殊鱗型系",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "煙燻基因複合珍珠鱗隱性基因 (p/p)",
    swimmingLayer: "中層水域",
    temperament: "溫和優雅",
    diet: "高品質薄片、赤蟲、豐年蝦",
    substrate: "天然細緻砂",
    waterFlow: "中等水流",
    craftsmanTip: "珍珠鱗突變使每片魚鱗凹凸起伏如微型鑽石鏡面。在煙燻的灰黑漸層底色上，折射出繁星般的璀璨碎光。",
    citesStatus: "精品閃光鱗系",
    accentColor: "#64748b",
    badge: "星塵鑽石珍珠鱗",
    featured: false,
    image: "images2/84.( Smokey Pearlscale ).png",
    tags: ["煙燻珍珠鱗", "鑽石反光", "立體鱗片", "璀璨碎光"]
  },
  {
    id: "angel-35",
    code: "ANGEL-CHOC-PEARL",
    name: "巧克力珍珠鱗神仙 (可可鑽石鱗神仙)",
    enName: "Chocolate Pearlscale Angelfish",
    sciName: "Pterophyllum scalare var. \"Chocolate Pearlscale (Sm/Sm, p/p)\"",
    category: "angelfish",
    categoryLabel: "特殊鱗型系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.0,
    origin: "雙煙燻基因複合珍珠鱗基因 (p/p)",
    swimmingLayer: "中層水域",
    temperament: "優雅靜謐",
    diet: "特級微粒、赤蟲、豐年蝦幼蟲",
    substrate: "淺色天然砂",
    waterFlow: "中等緩流",
    craftsmanTip: "深濃可可色澤與凹凸起伏的珍珠鱗相結合，在燈光搖曳下折射出金屬古銅與黑曜石般的高級光影反差。",
    citesStatus: "大師級繁育珍品",
    accentColor: "#451a03",
    badge: "黑曜石鑽石鱗",
    featured: false,
    image: "images2/85.( Chocolate Pearlscale ).png",
    tags: ["巧克力珍珠鱗", "古銅金屬光", "黑曜石折射", "精品品系"]
  },
  {
    id: "angel-36",
    code: "ANGEL-SMK-VEIL",
    name: "煙燻紗尾神仙 (煙燻燕尾神仙)",
    enName: "Smokey Veil Angelfish",
    sciName: "Pterophyllum scalare var. \"Smokey Veil (Sm/+, V/+)\"",
    category: "angelfish",
    categoryLabel: "長鰭紗尾系",
    difficulty: 3,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 18.0,
    origin: "煙燻基因複合長尾基因 (V/+)",
    swimmingLayer: "中層寬闊水域",
    temperament: "飄逸優雅 / 避免混養咬鰭魚種",
    diet: "浮性薄片、赤蟲、微肉食顆粒",
    substrate: "避免尖銳造景石材",
    waterFlow: "微弱緩流 (保護長鰭)",
    craftsmanTip: "背鰭、臀鰭與尾鰭大幅延長，如半透明的黑色薄紗在水中悠悠曼舞。需配置平緩水流與圓滑造景以防鰭絲分叉。",
    citesStatus: "優雅長鰭品系",
    accentColor: "#64748b",
    badge: "水下黑紗曼舞",
    featured: false,
    image: "images2/86.( Smokey Veil ).png",
    tags: ["煙燻紗尾", "燕尾長鰭", "薄紗飄逸", "曼妙游姿"]
  },
  {
    id: "angel-37",
    code: "ANGEL-CHOC-VEIL",
    name: "巧克力紗尾神仙 (可可燕尾神仙)",
    enName: "Chocolate Veil Angelfish",
    sciName: "Pterophyllum scalare var. \"Chocolate Veil (Sm/Sm, V/+)\"",
    category: "angelfish",
    categoryLabel: "長鰭紗尾系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 18.0,
    origin: "雙煙燻基因複合長尾基因 (V/+)",
    swimmingLayer: "中層水域",
    temperament: "端莊舒展",
    diet: "豐年蝦、赤蟲、高品質微粒",
    substrate: "天然細砂與柔軟水草",
    waterFlow: "極緩水流",
    craftsmanTip: "深濃可可色澤伴隨大幅度延伸的長鰭飄帶，游姿如宮廷禮服裙擺般舒展，展現極致華貴的水下姿態。",
    citesStatus: "頂級長鰭品系",
    accentColor: "#451a03",
    badge: "宮廷可可長裙",
    featured: false,
    image: "images2/87.( Chocolate Veil ).png",
    tags: ["巧克力紗尾", "長鰭飄帶", "宮廷華貴", "舒展姿態"]
  },
  {
    id: "angel-38",
    code: "ANGEL-PEARL-01",
    name: "珍珠鱗神仙 (鑽石鱗神仙)",
    enName: "Pearlscale Angelfish (Diamond Angel)",
    sciName: "Pterophyllum scalare var. \"Pearlscale (p/p)\"",
    category: "angelfish",
    categoryLabel: "特殊鱗型系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 15.0,
    origin: "珍珠鱗隱性純合基因 (p/p)",
    swimmingLayer: "中層水域",
    temperament: "溫和靈動",
    diet: "綜合薄片、赤蟲、豐年蝦",
    substrate: "深色底砂 (反射更耀眼)",
    waterFlow: "中等水流",
    craftsmanTip: "最具代表性的鱗片突變品系，每片魚鱗皆呈波浪狀立體反光，迎光游動時宛如無數碎鑽鋪滿全身，光彩奪目。",
    citesStatus: "市場長青閃亮名品",
    accentColor: "#e2e8f0",
    badge: "水下百面碎鑽",
    featured: false,
    image: "images2/88.( Pearlscale ).png",
    tags: ["珍珠鱗", "鑽石神仙", "波浪鱗片", "耀眼光芒"]
  },
  {
    id: "angel-39",
    code: "ANGEL-VEIL-01",
    name: "紗尾神仙 (燕尾神仙 / 絲尾神仙)",
    enName: "Veiltail Angelfish",
    sciName: "Pterophyllum scalare var. \"Veiltail (V/+)\"",
    category: "angelfish",
    categoryLabel: "長鰭紗尾系",
    difficulty: 2,
    tempMin: 24,
    tempMax: 28,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 3,
    ghMax: 8,
    sizeCm: 18.0,
    origin: "顯性單長鰭基因 (V/+)",
    swimmingLayer: "中層開闊水域",
    temperament: "溫順悠然",
    diet: "各類優質薄片、赤蟲",
    substrate: "天然河砂",
    waterFlow: "緩流水流",
    craftsmanTip: "各鰭長度為普通神仙的 1.5 至 2 倍，尾鰭如絲綢羽毛般在水中徐徐律動，水族箱中呈現仙氣飄飄的舒緩節奏。",
    citesStatus: "常規熱門觀賞品系",
    accentColor: "#94a3b8",
    badge: "絲綢羽毛長鰭",
    featured: false,
    image: "images2/89.( Veil  Veiltail ).png",
    tags: ["紗尾神仙", "燕尾", "仙氣飄飄", "長鰭舒展"]
  },
  {
    id: "angel-40",
    code: "ANGEL-SUP-VEIL",
    name: "超級巨燕尾神仙 (超長紗尾神仙)",
    enName: "Superveil Angelfish",
    sciName: "Pterophyllum scalare var. \"Superveil (V/V)\"",
    category: "angelfish",
    categoryLabel: "長鰭紗尾系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 28,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 22.0,
    origin: "純合子雙長鰭基因 (V/V)",
    swimmingLayer: "中層深水水域 (> 55cm 水深)",
    temperament: "極度優雅緩慢 / 嚴禁混養好動魚隻",
    diet: "無節幼體、高品質赤蟲、易吞食微粒",
    substrate: "細砂、避免一切帶角硬景觀",
    waterFlow: "極微弱水流",
    craftsmanTip: "長鰭基因的終極形態，所有鰭條延伸超過普通神仙 3 倍以上，如瀑布流水般垂曳。需至少 60 cm 超深水族箱以供充分展鰭。",
    citesStatus: "頂級大師華麗品系",
    accentColor: "#cbd5e1",
    badge: "極致超長瀑布尾 22cm",
    featured: false,
    image: "images2/90.( Superveil ).png",
    tags: ["超級紗尾", "超長鰭條", "雙長尾基因", "極深水缸要求"]
  },
  {
    id: "angel-41",
    code: "ANGEL-PB-01",
    name: "菲律賓藍神仙 (藍彩神仙)",
    enName: "Philippine Blue Angelfish",
    sciName: "Pterophyllum scalare var. \"Philippine Blue (pb/pb)\"",
    category: "angelfish",
    categoryLabel: "菲律賓藍金屬系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.5,
    origin: "菲律賓選育之隱性藍光基因 (pb/pb)",
    swimmingLayer: "中層水域",
    temperament: "溫和優雅",
    diet: "螺旋藻薄片、豐年蝦、強化藍光微粒",
    substrate: "深色底砂與深色背景 (激發藍光)",
    waterFlow: "中等緩流",
    craftsmanTip: "當代神仙魚育種史上的革命性突破！通體散發如藍寶石與金屬天青石般的金屬冷艷藍光，弱酸性軟水中藍色愈發深邃凝練。",
    citesStatus: "全球高人氣精品名種",
    accentColor: "#0284c7",
    badge: "革命性金屬天青藍",
    featured: true,
    image: "images2/91.( Philippine Blue ).png",
    tags: ["菲律賓藍", "pb基因", "金屬冷光", "藍寶石光芒"]
  },
  {
    id: "angel-42",
    code: "ANGEL-BLUE-BLUSH",
    name: "藍紅腮神仙 (藍胭脂神仙)",
    enName: "Blue Blushing Angelfish",
    sciName: "Pterophyllum scalare var. \"Blue Blushing (pb/pb, S/S)\"",
    category: "angelfish",
    categoryLabel: "菲律賓藍金屬系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.0,
    origin: "菲律賓藍基因複合雙無紋基因 (pb/pb, S/S)",
    swimmingLayer: "中層水域",
    temperament: "溫順害羞",
    diet: "豐年蝦幼蟲、特級微粒、赤蟲",
    substrate: "細緻天然砂",
    waterFlow: "中等緩流",
    craftsmanTip: "透明的鮮紅雙腮與全身披拂的天青金屬藍光形成極致色彩撞擊，在水下燈光映照下宛如藍水晶中嵌著兩顆紅寶石。",
    citesStatus: "精品繁育名種",
    accentColor: "#38bdf8",
    badge: "藍水晶嵌紅寶石",
    featured: false,
    image: "images2/92.( Blue Blushing ).png",
    tags: ["藍紅腮", "藍光胭脂", "冷暖色撞擊", "水晶質感"]
  },
  {
    id: "angel-43",
    code: "ANGEL-BLUE-KOI",
    name: "藍錦鯉神仙 (藍三色神仙)",
    enName: "Blue Koi Angelfish",
    sciName: "Pterophyllum scalare var. \"Blue Koi (pb/pb, Gm/Gm, S/S)\"",
    category: "angelfish",
    categoryLabel: "菲律賓藍金屬系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 16.0,
    origin: "菲律賓藍複合錦鯉三色多基因選育",
    swimmingLayer: "中層水域",
    temperament: "活潑好動 / 視覺衝擊力極強",
    diet: "豐年蝦、赤蟲、增色綜合薄片",
    substrate: "深色造景缸",
    waterFlow: "中等水流",
    craftsmanTip: "集金大理石、雙無紋、丹頂橘冠與菲律賓金屬藍光於一身，兼具紅、黑、白、藍四色絕美交融，是神仙魚育種的登峰造極之作。",
    citesStatus: "育種大師旗艦名作",
    accentColor: "#2563eb",
    badge: "四色神韻登峰造極",
    featured: true,
    image: "images2/93.( Blue Koi ).png",
    tags: ["藍錦鯉", "藍三色", "紅黑白藍四色", "育種巔峰"]
  },
  {
    id: "angel-44",
    code: "ANGEL-PLAT-01",
    name: "白金神仙 (極致純白金神仙)",
    enName: "Platinum Angelfish",
    sciName: "Pterophyllum scalare var. \"Platinum (g/g, pb/pb)\"",
    category: "angelfish",
    categoryLabel: "菲律賓藍金屬系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.0,
    origin: "黃金基因 (g/g) 複合菲律賓藍基因 (pb/pb)",
    swimmingLayer: "中層水域",
    temperament: "高貴純潔",
    diet: "高品質白魚粉薄片、豐年蝦",
    substrate: "深黑背景與深綠水草 (絕美反差)",
    waterFlow: "中等緩流",
    craftsmanTip: "黃金基因清除了所有黑色素，菲律賓藍基因則注入了冷光金屬色澤，全身散發如同頂級鉑金與白銀般的鏡面冷光，純淨無瑕。",
    citesStatus: "極受歡迎純色名品",
    accentColor: "#e0f2fe",
    badge: "鏡面純淨鉑金",
    featured: false,
    image: "images2/94.( Platinum ).png",
    tags: ["白金神仙", "白金冷光", "純色無暇", "鉑金光芒"]
  },
  {
    id: "angel-45",
    code: "ANGEL-PINOY-01",
    name: "Pinoy 神仙 (黑金屬藍神仙)",
    enName: "Pinoy Angelfish",
    sciName: "Pterophyllum scalare var. \"Pinoy (D/+, pb/pb)\"",
    category: "angelfish",
    categoryLabel: "Pinoy黑藍系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.5,
    origin: "黑化基因 (D/+) 複合純合菲律賓藍 (pb/pb)",
    swimmingLayer: "中層游動",
    temperament: "深沉高貴",
    diet: "赤蟲、豐年蝦、藍光增艷顆粒",
    substrate: "天然白砂或深色底砂皆宜",
    waterFlow: "中等緩流",
    craftsmanTip: "Pinoy（菲律賓語之意）代表著黑化基因與菲律賓藍的極致結晶。在墨黑底色上泛起深邃幽暗的孔雀天青藍光，如深海夜空中的極光。",
    citesStatus: "頂級育種品系",
    accentColor: "#1d4ed8",
    badge: "深邃黑夜極光藍",
    featured: false,
    image: "images2/95.( Pinoy ).png",
    tags: ["Pinoy", "黑藍神仙", "孔雀天青", "深邃暗夜光"]
  },
  {
    id: "angel-46",
    code: "ANGEL-PINOY-PARA",
    name: "Pinoy 帕拉伊巴神仙 (黑藍彩神仙)",
    enName: "Pinoy Paraiba Angelfish",
    sciName: "Pterophyllum scalare var. \"Pinoy Paraiba (D/+, pb/pb, S/S)\"",
    category: "angelfish",
    categoryLabel: "Pinoy黑藍系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.5,
    origin: "Pinoy 基因複合雙無紋胭脂基因 (S/S)",
    swimmingLayer: "中層水域",
    temperament: "優美沉穩",
    diet: "豐年蝦、赤蟲、微肉食微粒",
    substrate: "天然河砂",
    waterFlow: "中等緩流",
    craftsmanTip: "帕拉伊巴碧璽般的霓虹青藍覆蓋軀幹，配合透明胭脂紅鰓與黑化暗紋漸變，呈現如同珍稀帕拉伊巴寶石般迷幻的光彩。",
    citesStatus: "大師級珍稀收藏",
    accentColor: "#06b6d4",
    badge: "帕拉伊巴霓虹寶石",
    featured: false,
    image: "images2/96.( Pinoy Paraiba ).png",
    tags: ["Pinoy帕拉伊巴", "霓虹青藍", "寶石光澤", "頂級繁育"]
  },
  {
    id: "angel-47",
    code: "ANGEL-PARAIBA-01",
    name: "帕拉伊巴神仙 (碧璽藍彩神仙)",
    enName: "Paraiba Angelfish (Blue Blushing Ghost)",
    sciName: "Pterophyllum scalare var. \"Paraiba (pb/pb, S/S)\"",
    category: "angelfish",
    categoryLabel: "菲律賓藍金屬系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.0,
    origin: "菲律賓藍純合基因複合雙無紋基因",
    swimmingLayer: "中層游動",
    temperament: "溫順悠游",
    diet: "優質薄片、赤蟲、豐年蝦幼蟲",
    substrate: "天然細緻砂",
    waterFlow: "中等水流",
    craftsmanTip: "以世界最昂貴的藍綠色碧璽「帕拉伊巴」命名。無斑銀藍底色中散發透亮霓虹綠藍色澤，鰓部帶有一抹粉紅，極具靈氣。",
    citesStatus: "玩家級夢幻品系",
    accentColor: "#0891b2",
    badge: "霓虹碧璽靈氣藍",
    featured: false,
    image: "images2/97.( Paraiba ).png",
    tags: ["帕拉伊巴", "碧璽藍", "霓虹光澤", "夢幻神仙"]
  },
  {
    id: "angel-48",
    code: "ANGEL-TURQ-01",
    name: "綠松石神仙 (松石藍綠神仙)",
    enName: "Turquoise Angelfish",
    sciName: "Pterophyllum scalare var. \"Turquoise (pb/pb, g/+)\"",
    category: "angelfish",
    categoryLabel: "菲律賓藍金屬系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.5,
    origin: "菲律賓藍基因複合黃金基因選育",
    swimmingLayer: "中層水域",
    temperament: "活潑優雅",
    diet: "特級薄片、冷凍赤蟲、微粒",
    substrate: "深色底砂與水草造景",
    waterFlow: "中等水流",
    craftsmanTip: "微量黃色素與強烈金屬藍光在光學上疊加，誕生出罕見的綠松石色（藍綠色）水下金屬反光，游動時隨光線角度變換藍綠色彩。",
    citesStatus: "珍稀色系培育品",
    accentColor: "#0d9488",
    badge: "雙色變幻綠松石",
    featured: false,
    image: "images2/98.( Turquoise ).png",
    tags: ["綠松石神仙", "藍綠金屬光", "光學疊加", "稀有色調"]
  },
  {
    id: "angel-49",
    code: "ANGEL-BULG-01",
    name: "保加利亞重點色神仙 (海豹點神仙)",
    enName: "Bulgarian Sealpoint Angelfish",
    sciName: "Pterophyllum scalare var. \"Bulgarian Seal Point (bg/bg)\"",
    category: "angelfish",
    categoryLabel: "保加利亞重點色系",
    difficulty: 4,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.2,
    phMax: 7.2,
    ghMin: 2,
    ghMax: 7,
    sizeCm: 15.0,
    origin: "保加利亞繁育家選育之溫感重點色隱性基因 (bg/bg)",
    swimmingLayer: "中層水域",
    temperament: "溫和高雅",
    diet: "高品質冷凍餌料、高階薄片",
    substrate: "天然純淨細砂",
    waterFlow: "中等緩流",
    craftsmanTip: "如同暹羅貓般的溫度敏感型重點色突變！幼魚通體白金，隨生長吻部、背鰭尖端與尾鰭末端逐漸顯現如海豹皮毛般的濃黑重點色，極具傳奇色彩。",
    citesStatus: "歐洲殿堂級育種成果",
    accentColor: "#71717a",
    badge: "暹羅溫感重點色",
    featured: false,
    image: "images2/99.( Bulgarian Sealpoint ).png",
    tags: ["保加利亞重點色", "海豹點", "溫感基因", "歐洲育種傳奇"]
  },
  {
    id: "angel-50",
    code: "ANGEL-HYB-BLACK",
    name: "雜交極黑神仙 (混種黑金神仙)",
    enName: "Hybrid Black Angelfish",
    sciName: "Pterophyllum scalare var. \"Hybrid Black (D/D, g/g line)\"",
    category: "angelfish",
    categoryLabel: "極致黑化品系",
    difficulty: 3,
    tempMin: 25,
    tempMax: 29,
    phMin: 6.0,
    phMax: 7.0,
    ghMin: 2,
    ghMax: 6,
    sizeCm: 16.0,
    origin: "雙重深黑血系複合強健體質多重雜交",
    swimmingLayer: "中層沉木穿梭",
    temperament: "沉穩霸氣 / 體質強韌",
    diet: "沉底肉食顆粒、豐年蝦、赤蟲",
    substrate: "純淨河砂與深色岩石沉木",
    waterFlow: "中等水流",
    craftsmanTip: "克服了傳統雙黑神仙生長遲緩與體質脆弱的瓶頸，融合了強健雜交優勢與深邃如墨的無透光黑甲體色，展鰭威武剛勁，為第 100 號壓軸之作！",
    citesStatus: "大師級繁育改良結晶",
    accentColor: "#18181b",
    badge: "第100號壓軸黑甲王者",
    featured: true,
    image: "images2/100.( Hybrid Black ).png",
    tags: ["雜交極黑", "第100號", "壓軸王者", "強健黑化", "大師傑作"]
  }
];

if (typeof window !== 'undefined') {
  window.SPECIES_DATA = SPECIES_DATA;
}

